package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/ang-ee/angee-operator/api"
	"github.com/ang-ee/angee-operator/internal/operator/gql/model"
	"github.com/ang-ee/angee-operator/internal/service"
)

// Compose is the resolver for the compose field.
func (r *compiledStackResolver) Compose(ctx context.Context, obj *service.CompiledStack) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return yamlTaggedMap(obj.Compose)
}

// ProcessCompose is the resolver for the processCompose field.
func (r *compiledStackResolver) ProcessCompose(ctx context.Context, obj *service.CompiledStack) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return yamlTaggedMap(obj.ProcessCompose)
}

// SecretEnvVars is the resolver for the secretEnvVars field.
func (r *compiledStackResolver) SecretEnvVars(ctx context.Context, obj *service.CompiledStack) ([]*model.KeyValue, error) {
	if obj == nil {
		return nil, nil
	}
	return keyValueList(obj.SecretEnvVars), nil
}

// StackInit is the resolver for the stackInit field.
func (r *mutationResolver) StackInit(ctx context.Context, input model.StackInitInput) (*model.StackInitResult, error) {
	result, err := r.Platform.StackInit(ctx, input.Template, stringPtrValue(input.Path), keyValuesFrom(input.Inputs), boolPtrValue(input.Force))
	if err != nil {
		return nil, err
	}
	return &model.StackInitResult{Status: "initialized", Template: result.Template, Root: result.Root}, nil
}

// StackUpdate is the resolver for the stackUpdate field.
func (r *mutationResolver) StackUpdate(ctx context.Context) (*model.MutationResult, error) {
	if err := r.Platform.StackUpdate(ctx); err != nil {
		return nil, err
	}
	return actionResult("updated"), nil
}

// StackPrepare is the resolver for the stackPrepare field.
func (r *mutationResolver) StackPrepare(ctx context.Context) (*service.CompiledStack, error) {
	return r.Platform.StackPrepare(ctx)
}

// StackBuild is the resolver for the stackBuild field.
func (r *mutationResolver) StackBuild(ctx context.Context, input *model.StackRuntimeInput) (*model.MutationResult, error) {
	req := stackRuntimeRequest(input)
	if err := r.Platform.StackBuild(ctx, req.Services); err != nil {
		return nil, err
	}
	return actionResult("built"), nil
}

// StackUp is the resolver for the stackUp field.
func (r *mutationResolver) StackUp(ctx context.Context, input *model.StackRuntimeInput) (*model.MutationResult, error) {
	req := stackRuntimeRequest(input)
	if err := r.Platform.StackUp(ctx, req.Services, req.Build); err != nil {
		return nil, err
	}
	return actionResult("started"), nil
}

// StackDev is the resolver for the stackDev field.
func (r *mutationResolver) StackDev(ctx context.Context, input *model.StackRuntimeInput) (*model.MutationResult, error) {
	req := stackRuntimeRequest(input)
	if err := r.Platform.StackDev(ctx, req.Build); err != nil {
		return nil, err
	}
	return actionResult("started"), nil
}

// StackDown is the resolver for the stackDown field.
func (r *mutationResolver) StackDown(ctx context.Context) (*model.MutationResult, error) {
	if err := r.Platform.StackDown(ctx); err != nil {
		return nil, err
	}
	return actionResult("stopped"), nil
}

// StackDestroy is the resolver for the stackDestroy field.
func (r *mutationResolver) StackDestroy(ctx context.Context, purge *bool) (*model.MutationResult, error) {
	if err := r.Platform.StackDestroy(ctx, boolPtrValue(purge)); err != nil {
		return nil, err
	}
	return actionResult("destroyed"), nil
}

// JobRun is the resolver for the jobRun field.
func (r *mutationResolver) JobRun(ctx context.Context, name string, inputs []*model.KeyValueInput) (string, error) {
	out, err := r.Platform.JobRun(ctx, name, keyValuesFrom(inputs))
	if err != nil {
		return "", err
	}
	return string(out), nil
}

// ServiceInit is the resolver for the serviceInit field.
func (r *mutationResolver) ServiceInit(ctx context.Context, input model.ServiceInput) (*model.MutationResult, error) {
	req := serviceRequestFrom(input)
	if err := r.Platform.ServiceInit(ctx, req); err != nil {
		return nil, err
	}
	return namedActionResult("created", req.Name), nil
}

// ServiceCreate is the resolver for the serviceCreate field.
func (r *mutationResolver) ServiceCreate(ctx context.Context, input model.ServiceCreateInput) (*api.ServiceState, error) {
	state, err := r.Platform.ServiceCreate(ctx, serviceCreateRequestFrom(input))
	if err != nil {
		return nil, err
	}
	return &state, nil
}

// ServiceUpdate is the resolver for the serviceUpdate field.
func (r *mutationResolver) ServiceUpdate(ctx context.Context, name string, input model.ServiceInput) (*model.MutationResult, error) {
	req := serviceRequestFrom(input)
	req.Name = name
	if err := r.Platform.ServiceUpdate(ctx, req); err != nil {
		return nil, err
	}
	return namedActionResult("updated", req.Name), nil
}

// ServiceUp is the resolver for the serviceUp field.
func (r *mutationResolver) ServiceUp(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceUp(ctx, []string{name}); err != nil {
		return nil, err
	}
	return namedActionResult("up", name), nil
}

// ServiceStart is the resolver for the serviceStart field.
func (r *mutationResolver) ServiceStart(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceStart(ctx, []string{name}); err != nil {
		return nil, err
	}
	return namedActionResult("started", name), nil
}

// ServiceStop is the resolver for the serviceStop field.
func (r *mutationResolver) ServiceStop(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceStop(ctx, []string{name}); err != nil {
		return nil, err
	}
	return namedActionResult("stopped", name), nil
}

// ServiceRestart is the resolver for the serviceRestart field.
func (r *mutationResolver) ServiceRestart(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceRestart(ctx, []string{name}); err != nil {
		return nil, err
	}
	return namedActionResult("restarted", name), nil
}

// ServiceDestroy is the resolver for the serviceDestroy field.
func (r *mutationResolver) ServiceDestroy(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceDestroy(ctx, name, true); err != nil {
		return nil, err
	}
	return namedActionResult("destroyed", name), nil
}

// SourceFetch is the resolver for the sourceFetch field.
func (r *mutationResolver) SourceFetch(ctx context.Context, name string) (*api.SourceState, error) {
	state, err := r.Platform.SourceFetch(ctx, name)
	return &state, err
}

// SourcePull is the resolver for the sourcePull field.
func (r *mutationResolver) SourcePull(ctx context.Context, name string) (*api.SourceState, error) {
	state, err := r.Platform.SourcePull(ctx, name)
	return &state, err
}

// SourcePush is the resolver for the sourcePush field.
func (r *mutationResolver) SourcePush(ctx context.Context, name string, ref *string) (*api.SourceState, error) {
	state, err := r.Platform.SourcePush(ctx, name, stringPtrValue(ref))
	return &state, err
}

// WorkspaceCreate is the resolver for the workspaceCreate field.
func (r *mutationResolver) WorkspaceCreate(ctx context.Context, input model.WorkspaceCreateInput) (*api.WorkspaceRef, error) {
	ref, err := r.Platform.WorkspaceCreate(ctx, workspaceCreateRequestFrom(input))
	return &ref, err
}

// WorkspaceUpdate is the resolver for the workspaceUpdate field.
func (r *mutationResolver) WorkspaceUpdate(ctx context.Context, name string, input model.WorkspaceUpdateInput) (*api.WorkspaceRef, error) {
	ref, err := r.Platform.WorkspaceUpdate(ctx, name, keyValuesFrom(input.Inputs), stringPtrValue(input.TTL))
	return &ref, err
}

// WorkspaceDestroy is the resolver for the workspaceDestroy field.
func (r *mutationResolver) WorkspaceDestroy(ctx context.Context, name string, purge *bool) (*model.MutationResult, error) {
	if err := r.Platform.WorkspaceDestroy(ctx, name, boolPtrValue(purge)); err != nil {
		return nil, err
	}
	return namedActionResult("destroyed", name), nil
}

// WorkspacePush is the resolver for the workspacePush field.
func (r *mutationResolver) WorkspacePush(ctx context.Context, name string, ref *string) ([]*api.SourceState, error) {
	states, err := r.Platform.WorkspacePush(ctx, name, stringPtrValue(ref))
	return ptrSlice(states), err
}

// WorkspaceSyncBase is the resolver for the workspaceSyncBase field.
func (r *mutationResolver) WorkspaceSyncBase(ctx context.Context, name string, method *string) ([]*api.SourceState, error) {
	states, err := r.Platform.WorkspaceSyncBase(ctx, name, stringPtrValue(method))
	return ptrSlice(states), err
}

// WorkspaceSourceFetch is the resolver for the workspaceSourceFetch field.
func (r *mutationResolver) WorkspaceSourceFetch(ctx context.Context, workspace string, slot string) (*api.WorkspaceSourceStatus, error) {
	status, err := r.Platform.WorkspaceSourceFetch(ctx, workspace, slot)
	return &status, err
}

// WorkspaceSourcePull is the resolver for the workspaceSourcePull field.
func (r *mutationResolver) WorkspaceSourcePull(ctx context.Context, workspace string, slot string) (*api.WorkspaceSourceStatus, error) {
	status, err := r.Platform.WorkspaceSourcePull(ctx, workspace, slot)
	return &status, err
}

// WorkspaceSourcePush is the resolver for the workspaceSourcePush field.
func (r *mutationResolver) WorkspaceSourcePush(ctx context.Context, workspace string, slot string, ref *string) (*api.WorkspaceSourceStatus, error) {
	status, err := r.Platform.WorkspaceSourcePush(ctx, workspace, slot, stringPtrValue(ref))
	return &status, err
}

// WorkspaceCreatePreflight is the resolver for the workspaceCreatePreflight field.
func (r *mutationResolver) WorkspaceCreatePreflight(ctx context.Context, input model.WorkspaceCreateInput) (*api.WorkspaceCreatePreflightResponse, error) {
	resp, err := r.Platform.WorkspaceCreatePreflight(ctx, workspaceCreateRequestFrom(input))
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// MintConnectionToken is the resolver for the mintConnectionToken field.
func (r *mutationResolver) MintConnectionToken(ctx context.Context, actor string, scope []string, ttl *string) (*api.ConnectionTokenResponse, error) {
	if r.Tokens == nil {
		return nil, errSubscriptionsUnavailable
	}
	resp, err := r.Tokens.MintConnection(actor, scope, stringPtrValue(ttl))
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// MintRouteToken is the resolver for the mintRouteToken field.
func (r *mutationResolver) MintRouteToken(ctx context.Context, actor string, service string, ttl *string) (*api.ConnectionTokenResponse, error) {
	if r.Tokens == nil {
		return nil, errSubscriptionsUnavailable
	}
	resp, err := r.Tokens.MintRoute(actor, service, stringPtrValue(ttl))
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// WorkspaceSourceMerge is the resolver for the workspaceSourceMerge field.
func (r *mutationResolver) WorkspaceSourceMerge(ctx context.Context, workspace string, slot string, ref string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceMerge(ctx, workspace, slot, ref)
	return &res, err
}

// WorkspaceSourceRebase is the resolver for the workspaceSourceRebase field.
func (r *mutationResolver) WorkspaceSourceRebase(ctx context.Context, workspace string, slot string, ref string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceRebase(ctx, workspace, slot, ref)
	return &res, err
}

// WorkspaceSourceMergeAbort is the resolver for the workspaceSourceMergeAbort field.
func (r *mutationResolver) WorkspaceSourceMergeAbort(ctx context.Context, workspace string, slot string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceMergeAbort(ctx, workspace, slot)
	return &res, err
}

// WorkspaceSourceRebaseAbort is the resolver for the workspaceSourceRebaseAbort field.
func (r *mutationResolver) WorkspaceSourceRebaseAbort(ctx context.Context, workspace string, slot string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceRebaseAbort(ctx, workspace, slot)
	return &res, err
}

// WorkspaceSourceRebaseContinue is the resolver for the workspaceSourceRebaseContinue field.
func (r *mutationResolver) WorkspaceSourceRebaseContinue(ctx context.Context, workspace string, slot string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceRebaseContinue(ctx, workspace, slot)
	return &res, err
}

// WorkspaceSourcePublish is the resolver for the workspaceSourcePublish field.
func (r *mutationResolver) WorkspaceSourcePublish(ctx context.Context, workspace string, slot string, remote *string, branch *string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourcePublish(ctx, workspace, slot, stringPtrValue(remote), stringPtrValue(branch))
	return &res, err
}

// SecretSet is the resolver for the secretSet field.
func (r *mutationResolver) SecretSet(ctx context.Context, name string, value string) (*api.SecretRef, error) {
	ref, err := r.Platform.SecretSet(ctx, name, value)
	if err != nil {
		return nil, err
	}
	return &ref, nil
}

// SecretDelete is the resolver for the secretDelete field.
func (r *mutationResolver) SecretDelete(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.SecretDelete(ctx, name); err != nil {
		return nil, err
	}
	return namedActionResult("deleted", name), nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.MutationResult, error) {
	return actionResult("ok"), nil
}

// StackStatus is the resolver for the stackStatus field.
func (r *queryResolver) StackStatus(ctx context.Context) (*api.StackStatusResponse, error) {
	status, err := r.Platform.StackStatus(ctx)
	return &status, err
}

// ServiceEndpoint is the resolver for the serviceEndpoint field.
func (r *queryResolver) ServiceEndpoint(ctx context.Context, name string) (*api.ServiceEndpoint, error) {
	return r.Platform.ServiceEndpoint(ctx, name)
}

// IngressStatus is the resolver for the ingressStatus field.
func (r *queryResolver) IngressStatus(ctx context.Context) (*api.IngressStatus, error) {
	return r.Platform.IngressStatus(ctx)
}

// Services is the resolver for the services field.
func (r *queryResolver) Services(ctx context.Context) ([]*api.ServiceState, error) {
	services, err := r.Platform.ServiceList(ctx)
	return ptrSlice(services), err
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context) ([]*api.JobState, error) {
	jobs, err := r.Platform.JobList(ctx)
	return ptrSlice(jobs), err
}

// Sources is the resolver for the sources field.
func (r *queryResolver) Sources(ctx context.Context) ([]*api.SourceState, error) {
	sources, err := r.Platform.SourceList(ctx)
	return ptrSlice(sources), err
}

// Source is the resolver for the source field.
func (r *queryResolver) Source(ctx context.Context, name string) (*api.SourceState, error) {
	state, err := r.Platform.SourceStatus(ctx, name)
	return &state, err
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context) ([]*api.WorkspaceRef, error) {
	workspaces, err := r.Platform.WorkspaceList(ctx)
	return ptrSlice(workspaces), err
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context, name string) (*api.WorkspaceRef, error) {
	workspace, err := r.Platform.WorkspaceGet(ctx, name)
	return &workspace, err
}

// WorkspaceStatus is the resolver for the workspaceStatus field.
func (r *queryResolver) WorkspaceStatus(ctx context.Context, name string) (*api.WorkspaceStatusResponse, error) {
	status, err := r.Platform.WorkspaceStatus(ctx, name)
	return &status, err
}

// WorkspaceGit is the resolver for the workspaceGit field.
func (r *queryResolver) WorkspaceGit(ctx context.Context, name string) ([]*api.SourceState, error) {
	states, err := r.Platform.WorkspaceGitStatus(ctx, name)
	return ptrSlice(states), err
}

// GitOpsTopology is the resolver for the gitOpsTopology field.
func (r *queryResolver) GitOpsTopology(ctx context.Context, withCommits *int) (*api.GitOpsTopologyResponse, error) {
	limit := 0
	if withCommits != nil {
		limit = *withCommits
	}
	topology, err := r.Platform.GitOpsTopologyWithCommits(ctx, limit)
	return &topology, err
}

// SourceDiff is the resolver for the sourceDiff field.
func (r *queryResolver) SourceDiff(ctx context.Context, name string, ref *string) ([]*api.DiffFile, error) {
	files, err := r.Platform.SourceDiff(ctx, name, stringPtrValue(ref))
	if err != nil {
		return nil, err
	}
	out := make([]*api.DiffFile, len(files))
	for i := range files {
		out[i] = &files[i]
	}
	return out, nil
}

// WorkspaceSourceDiff is the resolver for the workspaceSourceDiff field.
func (r *queryResolver) WorkspaceSourceDiff(ctx context.Context, workspace string, slot string, ref *string) ([]*api.DiffFile, error) {
	files, err := r.Platform.WorkspaceSourceDiff(ctx, workspace, slot, stringPtrValue(ref))
	if err != nil {
		return nil, err
	}
	out := make([]*api.DiffFile, len(files))
	for i := range files {
		out[i] = &files[i]
	}
	return out, nil
}

// StackLogs is the resolver for the stackLogs field.
func (r *queryResolver) StackLogs(ctx context.Context, services []string, limit *int) (string, error) {
	maxBytes := logLimitValue(limit)
	logs, err := r.Platform.StackLogsLimited(ctx, services, false, maxBytes)
	if err != nil {
		return "", err
	}
	return collectLogStream(logs, maxBytes), nil
}

// ServiceLogs is the resolver for the serviceLogs field.
func (r *queryResolver) ServiceLogs(ctx context.Context, name string, limit *int) (string, error) {
	maxBytes := logLimitValue(limit)
	logs, err := r.Platform.StackLogsLimited(ctx, []string{name}, false, maxBytes)
	if err != nil {
		return "", err
	}
	return collectLogStream(logs, maxBytes), nil
}

// WorkspaceLogs is the resolver for the workspaceLogs field.
func (r *queryResolver) WorkspaceLogs(ctx context.Context, name string, limit *int) (string, error) {
	maxBytes := logLimitValue(limit)
	logs, err := r.Platform.WorkspaceLogsLimited(ctx, name, false, maxBytes)
	if err != nil {
		return "", err
	}
	return collectLogStream(logs, maxBytes), nil
}

// McpDescriptor is the resolver for the mcpDescriptor field.
func (r *queryResolver) McpDescriptor(ctx context.Context) (map[string]any, error) {
	return mcpDescriptor(), nil
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context) ([]*api.TemplateDescriptor, error) {
	descriptors, err := r.Platform.Templates(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*api.TemplateDescriptor, len(descriptors))
	for i := range descriptors {
		out[i] = &descriptors[i]
	}
	return out, nil
}

// Template is the resolver for the template field.
func (r *queryResolver) Template(ctx context.Context, ref string) (*api.TemplateDescriptor, error) {
	desc, err := r.Platform.Template(ctx, ref)
	if err != nil {
		return nil, err
	}
	return &desc, nil
}

// Secrets is the resolver for the secrets field.
func (r *queryResolver) Secrets(ctx context.Context) ([]*api.SecretRef, error) {
	refs, err := r.Platform.SecretsList(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*api.SecretRef, len(refs))
	for i := range refs {
		out[i] = &refs[i]
	}
	return out, nil
}

// Secret is the resolver for the secret field.
func (r *queryResolver) Secret(ctx context.Context, name string) (*api.SecretRef, error) {
	ref, err := r.Platform.SecretGet(ctx, name)
	if err != nil {
		return nil, err
	}
	return &ref, nil
}

// SecretValue is the resolver for the secretValue field.
func (r *queryResolver) SecretValue(ctx context.Context, name string) (*api.SecretValueResponse, error) {
	resp, err := r.Platform.SecretValue(ctx, name)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Services is the resolver for the services field.
func (r *stackStatusResolver) Services(ctx context.Context, obj *api.StackStatusResponse) ([]*api.ServiceState, error) {
	if obj == nil {
		return nil, nil
	}
	return ptrSlice(sortedMapValues(obj.Services)), nil
}

// Jobs is the resolver for the jobs field.
func (r *stackStatusResolver) Jobs(ctx context.Context, obj *api.StackStatusResponse) ([]*api.JobState, error) {
	if obj == nil {
		return nil, nil
	}
	return ptrSlice(sortedMapValues(obj.Jobs)), nil
}

// Workspaces is the resolver for the workspaces field.
func (r *stackStatusResolver) Workspaces(ctx context.Context, obj *api.StackStatusResponse) ([]*api.WorkspaceRef, error) {
	if obj == nil {
		return nil, nil
	}
	return ptrSlice(sortedMapValues(obj.Workspaces)), nil
}

// OnGitOpsTopologyChange is the resolver for the onGitOpsTopologyChange field.
func (r *subscriptionResolver) OnGitOpsTopologyChange(ctx context.Context) (<-chan *api.GitOpsTopologyResponse, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeTopology(ctx), nil
}

// OnServiceLogs is the resolver for the onServiceLogs field.
func (r *subscriptionResolver) OnServiceLogs(ctx context.Context, name string) (<-chan string, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeServiceLogs(ctx, name)
}

// OnWorkspaceLogs is the resolver for the onWorkspaceLogs field.
func (r *subscriptionResolver) OnWorkspaceLogs(ctx context.Context, name string) (<-chan string, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeWorkspaceLogs(ctx, name)
}

// OnWorkspaceStatusChange is the resolver for the onWorkspaceStatusChange field.
func (r *subscriptionResolver) OnWorkspaceStatusChange(ctx context.Context, name string) (<-chan *api.WorkspaceStatusResponse, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeWorkspaceStatus(ctx, name), nil
}

// OnStackSnapshotChange is the resolver for the onStackSnapshotChange field.
func (r *subscriptionResolver) OnStackSnapshotChange(ctx context.Context) (<-chan *model.StackSnapshot, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeSnapshot(ctx), nil
}

// EffectiveInputs is the resolver for the effectiveInputs field.
func (r *workspaceCreatePreflightResolver) EffectiveInputs(ctx context.Context, obj *api.WorkspaceCreatePreflightResponse) ([]*model.KeyValue, error) {
	if obj == nil {
		return nil, nil
	}
	return keyValueList(obj.EffectiveInputs), nil
}

// TTLExpiresAt is the resolver for the ttlExpiresAt field.
func (r *workspaceRefResolver) TTLExpiresAt(ctx context.Context, obj *api.WorkspaceRef) (*string, error) {
	if obj == nil {
		return nil, nil
	}
	return formatGraphQLTime(obj.TTLExpiresAt), nil
}

// Inputs is the resolver for the inputs field.
func (r *workspaceStatusResolver) Inputs(ctx context.Context, obj *api.WorkspaceStatusResponse) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return stringMapJSON(obj.Inputs), nil
}

// Allocations is the resolver for the allocations field.
func (r *workspaceStatusResolver) Allocations(ctx context.Context, obj *api.WorkspaceStatusResponse) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return intMapJSON(obj.Allocations), nil
}

// PersistPaths is the resolver for the persistPaths field.
func (r *workspaceStatusResolver) PersistPaths(ctx context.Context, obj *api.WorkspaceStatusResponse) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return anyMapJSON(obj.PersistPaths), nil
}

// TTLExpiresAt is the resolver for the ttlExpiresAt field.
func (r *workspaceStatusResolver) TTLExpiresAt(ctx context.Context, obj *api.WorkspaceStatusResponse) (*string, error) {
	if obj == nil {
		return nil, nil
	}
	return formatGraphQLTime(obj.TTLExpiresAt), nil
}

// CompiledStack returns CompiledStackResolver implementation.
func (r *Resolver) CompiledStack() CompiledStackResolver { return &compiledStackResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// StackStatus returns StackStatusResolver implementation.
func (r *Resolver) StackStatus() StackStatusResolver { return &stackStatusResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// WorkspaceCreatePreflight returns WorkspaceCreatePreflightResolver implementation.
func (r *Resolver) WorkspaceCreatePreflight() WorkspaceCreatePreflightResolver {
	return &workspaceCreatePreflightResolver{r}
}

// WorkspaceRef returns WorkspaceRefResolver implementation.
func (r *Resolver) WorkspaceRef() WorkspaceRefResolver { return &workspaceRefResolver{r} }

// WorkspaceStatus returns WorkspaceStatusResolver implementation.
func (r *Resolver) WorkspaceStatus() WorkspaceStatusResolver { return &workspaceStatusResolver{r} }

type compiledStackResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type stackStatusResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type workspaceCreatePreflightResolver struct{ *Resolver }
type workspaceRefResolver struct{ *Resolver }
type workspaceStatusResolver struct{ *Resolver }
