package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/ang-ee/angee-operator/api"
	"github.com/ang-ee/angee-operator/internal/operator/gql/model"
	"github.com/ang-ee/angee-operator/internal/query"
	"github.com/ang-ee/angee-operator/internal/queryfields"
	"github.com/ang-ee/angee-operator/internal/service"
)

// Compose is the resolver for the compose field.
func (r *compiledStackResolver) Compose(ctx context.Context, obj *service.CompiledStack) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return yamlTaggedMap(obj.Compose)
}

// ProcessCompose is the resolver for the processCompose field.
func (r *compiledStackResolver) ProcessCompose(ctx context.Context, obj *service.CompiledStack) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return yamlTaggedMap(obj.ProcessCompose)
}

// SecretEnvVars is the resolver for the secretEnvVars field.
func (r *compiledStackResolver) SecretEnvVars(ctx context.Context, obj *service.CompiledStack) ([]*model.KeyValue, error) {
	if obj == nil {
		return nil, nil
	}
	return keyValueList(obj.SecretEnvVars), nil
}

// Sources is the resolver for the sources field.
func (r *gitOpsTopologyResolver) Sources(ctx context.Context, obj *api.GitOpsTopologyResponse, filter *model.SourceStateFilter, sorting []*model.SourceStateSort, paging *model.OffsetPaging) (*model.SourceStateConnection, error) {
	var items []api.SourceState
	if obj != nil {
		items = obj.Sources
	}
	args := query.Args{Filter: bindSourceFilter(filter), Sorting: bindSourceSorts(sorting), Paging: bindPaging(paging)}
	page, total := query.Apply(items, args, queryfields.Source)
	return &model.SourceStateConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Workspaces is the resolver for the workspaces field.
func (r *gitOpsTopologyResolver) Workspaces(ctx context.Context, obj *api.GitOpsTopologyResponse, filter *model.WorkspaceStatusFilter, sorting []*model.WorkspaceStatusSort, paging *model.OffsetPaging) (*model.WorkspaceStatusConnection, error) {
	var items []api.WorkspaceStatusResponse
	if obj != nil {
		items = obj.Workspaces
	}
	args := query.Args{Filter: bindWorkspaceStatusFilter(filter), Sorting: bindWorkspaceStatusSorts(sorting), Paging: bindPaging(paging)}
	page, total := query.Apply(items, args, queryfields.WorkspaceStatus)
	return &model.WorkspaceStatusConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Links is the resolver for the links field.
func (r *gitOpsTopologyResolver) Links(ctx context.Context, obj *api.GitOpsTopologyResponse, filter *model.GitOpsLinkFilter, sorting []*model.GitOpsLinkSort, paging *model.OffsetPaging) (*model.GitOpsLinkConnection, error) {
	var items []api.GitOpsLink
	if obj != nil {
		items = obj.Links
	}
	args := query.Args{Filter: bindGitOpsLinkFilter(filter), Sorting: bindGitOpsLinkSorts(sorting), Paging: bindPaging(paging)}
	page, total := query.Apply(items, args, queryfields.GitOpsLink)
	return &model.GitOpsLinkConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// ID is the resolver for the id field.
func (r *jobStateResolver) ID(ctx context.Context, obj *api.JobState) (string, error) {
	return obj.Name, nil
}

// StackInit is the resolver for the stackInit field.
func (r *mutationResolver) StackInit(ctx context.Context, input model.StackInitInput) (*model.StackInitResult, error) {
	result, err := r.Platform.StackInit(ctx, input.Template, stringPtrValue(input.Path), keyValuesFrom(input.Inputs), boolPtrValue(input.Force))
	if err != nil {
		return nil, err
	}
	return &model.StackInitResult{Status: "initialized", Template: result.Template, Root: result.Root}, nil
}

// StackUpdate is the resolver for the stackUpdate field.
func (r *mutationResolver) StackUpdate(ctx context.Context) (*model.MutationResult, error) {
	if err := r.Platform.StackUpdate(ctx); err != nil {
		return nil, err
	}
	return actionResult("updated"), nil
}

// StackPrepare is the resolver for the stackPrepare field.
func (r *mutationResolver) StackPrepare(ctx context.Context) (*service.CompiledStack, error) {
	return r.Platform.StackPrepare(ctx)
}

// StackBuild is the resolver for the stackBuild field.
func (r *mutationResolver) StackBuild(ctx context.Context, input *model.StackRuntimeInput) (*model.MutationResult, error) {
	req := stackRuntimeRequest(input)
	if err := r.Platform.StackBuild(ctx, req.Services); err != nil {
		return nil, err
	}
	return actionResult("built"), nil
}

// StackUp is the resolver for the stackUp field.
func (r *mutationResolver) StackUp(ctx context.Context, input *model.StackRuntimeInput) (*model.MutationResult, error) {
	req := stackRuntimeRequest(input)
	if err := r.Platform.StackUp(ctx, req.Services, req.Build); err != nil {
		return nil, err
	}
	return actionResult("started"), nil
}

// StackDev is the resolver for the stackDev field.
func (r *mutationResolver) StackDev(ctx context.Context, input *model.StackRuntimeInput) (*model.MutationResult, error) {
	req := stackRuntimeRequest(input)
	if err := r.Platform.StackDev(ctx, req.Build); err != nil {
		return nil, err
	}
	return actionResult("started"), nil
}

// StackDown is the resolver for the stackDown field.
func (r *mutationResolver) StackDown(ctx context.Context) (*model.MutationResult, error) {
	if err := r.Platform.StackDown(ctx); err != nil {
		return nil, err
	}
	return actionResult("stopped"), nil
}

// StackDestroy is the resolver for the stackDestroy field.
func (r *mutationResolver) StackDestroy(ctx context.Context, purge *bool) (*model.MutationResult, error) {
	if err := r.Platform.StackDestroy(ctx, boolPtrValue(purge)); err != nil {
		return nil, err
	}
	return actionResult("destroyed"), nil
}

// JobRun is the resolver for the jobRun field.
func (r *mutationResolver) JobRun(ctx context.Context, name string, inputs []*model.KeyValueInput) (string, error) {
	out, err := r.Platform.JobRun(ctx, name, keyValuesFrom(inputs))
	if err != nil {
		return "", err
	}
	return string(out), nil
}

// ServiceInit is the resolver for the serviceInit field.
func (r *mutationResolver) ServiceInit(ctx context.Context, input model.ServiceInput) (*model.MutationResult, error) {
	req := serviceRequestFrom(input)
	if err := r.Platform.ServiceInit(ctx, req); err != nil {
		return nil, err
	}
	return namedActionResult("created", req.Name), nil
}

// CreateOneService is the resolver for the createOneService field.
func (r *mutationResolver) CreateOneService(ctx context.Context, input model.CreateOneServiceInput) (*api.ServiceState, error) {
	state, err := r.Platform.ServiceCreate(ctx, serviceCreateRequestFrom(*input.Service))
	if err != nil {
		return nil, err
	}
	return &state, nil
}

// UpdateOneService is the resolver for the updateOneService field.
func (r *mutationResolver) UpdateOneService(ctx context.Context, input model.UpdateOneServiceInput) (*api.ServiceState, error) {
	req := serviceRequestFrom(*input.Update)
	req.Name = input.ID
	if err := r.Platform.ServiceUpdate(ctx, req); err != nil {
		return nil, err
	}
	state, err := r.serviceByID(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	if state == nil {
		return nil, fmt.Errorf("service %q not found after update", input.ID)
	}
	return state, nil
}

// DeleteOneService is the resolver for the deleteOneService field.
func (r *mutationResolver) DeleteOneService(ctx context.Context, input model.DeleteOneServiceInput) (*api.ServiceState, error) {
	prev, err := r.serviceByID(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	if prev == nil {
		return nil, fmt.Errorf("service %q not found", input.ID)
	}
	if err := r.Platform.ServiceDestroy(ctx, input.ID, true); err != nil {
		return nil, err
	}
	return prev, nil
}

// ServiceUp is the resolver for the serviceUp field.
func (r *mutationResolver) ServiceUp(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceUp(ctx, []string{name}); err != nil {
		return nil, err
	}
	return namedActionResult("up", name), nil
}

// ServiceStart is the resolver for the serviceStart field.
func (r *mutationResolver) ServiceStart(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceStart(ctx, []string{name}); err != nil {
		return nil, err
	}
	return namedActionResult("started", name), nil
}

// ServiceStop is the resolver for the serviceStop field.
func (r *mutationResolver) ServiceStop(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceStop(ctx, []string{name}); err != nil {
		return nil, err
	}
	return namedActionResult("stopped", name), nil
}

// ServiceRestart is the resolver for the serviceRestart field.
func (r *mutationResolver) ServiceRestart(ctx context.Context, name string) (*model.MutationResult, error) {
	if err := r.Platform.ServiceRestart(ctx, []string{name}); err != nil {
		return nil, err
	}
	return namedActionResult("restarted", name), nil
}

// SourceFetch is the resolver for the sourceFetch field.
func (r *mutationResolver) SourceFetch(ctx context.Context, name string) (*api.SourceState, error) {
	state, err := r.Platform.SourceFetch(ctx, name)
	return &state, err
}

// SourcePull is the resolver for the sourcePull field.
func (r *mutationResolver) SourcePull(ctx context.Context, name string) (*api.SourceState, error) {
	state, err := r.Platform.SourcePull(ctx, name)
	return &state, err
}

// SourcePush is the resolver for the sourcePush field.
func (r *mutationResolver) SourcePush(ctx context.Context, name string, ref *string) (*api.SourceState, error) {
	state, err := r.Platform.SourcePush(ctx, name, stringPtrValue(ref))
	return &state, err
}

// CreateOneWorkspace is the resolver for the createOneWorkspace field.
func (r *mutationResolver) CreateOneWorkspace(ctx context.Context, input model.CreateOneWorkspaceInput) (*api.WorkspaceRef, error) {
	ref, err := r.Platform.WorkspaceCreate(ctx, workspaceCreateRequestFrom(*input.Workspace))
	if err != nil {
		return nil, err
	}
	return &ref, nil
}

// UpdateOneWorkspace is the resolver for the updateOneWorkspace field.
func (r *mutationResolver) UpdateOneWorkspace(ctx context.Context, input model.UpdateOneWorkspaceInput) (*api.WorkspaceRef, error) {
	ref, err := r.Platform.WorkspaceUpdate(ctx, input.ID, keyValuesFrom(input.Update.Inputs), stringPtrValue(input.Update.TTL))
	if err != nil {
		return nil, err
	}
	return &ref, nil
}

// DeleteOneWorkspace is the resolver for the deleteOneWorkspace field.
func (r *mutationResolver) DeleteOneWorkspace(ctx context.Context, input model.DeleteOneWorkspaceInput) (*api.WorkspaceRef, error) {
	// WorkspaceGet returns a not-found error for an unknown name, so capturing
	// the pre-delete record doubles as the existence check deleteOne implies.
	prev, err := r.Platform.WorkspaceGet(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	if err := r.Platform.WorkspaceDestroy(ctx, input.ID, boolPtrValue(input.Purge)); err != nil {
		return nil, err
	}
	return &prev, nil
}

// WorkspacePush is the resolver for the workspacePush field.
func (r *mutationResolver) WorkspacePush(ctx context.Context, name string, ref *string) ([]*api.SourceState, error) {
	states, err := r.Platform.WorkspacePush(ctx, name, stringPtrValue(ref))
	return ptrSlice(states), err
}

// WorkspaceSyncBase is the resolver for the workspaceSyncBase field.
func (r *mutationResolver) WorkspaceSyncBase(ctx context.Context, name string, method *string) ([]*api.SourceState, error) {
	states, err := r.Platform.WorkspaceSyncBase(ctx, name, stringPtrValue(method))
	return ptrSlice(states), err
}

// WorkspaceSourceFetch is the resolver for the workspaceSourceFetch field.
func (r *mutationResolver) WorkspaceSourceFetch(ctx context.Context, workspace string, slot string) (*api.WorkspaceSourceStatus, error) {
	status, err := r.Platform.WorkspaceSourceFetch(ctx, workspace, slot)
	return &status, err
}

// WorkspaceSourcePull is the resolver for the workspaceSourcePull field.
func (r *mutationResolver) WorkspaceSourcePull(ctx context.Context, workspace string, slot string) (*api.WorkspaceSourceStatus, error) {
	status, err := r.Platform.WorkspaceSourcePull(ctx, workspace, slot)
	return &status, err
}

// WorkspaceSourcePush is the resolver for the workspaceSourcePush field.
func (r *mutationResolver) WorkspaceSourcePush(ctx context.Context, workspace string, slot string, ref *string) (*api.WorkspaceSourceStatus, error) {
	status, err := r.Platform.WorkspaceSourcePush(ctx, workspace, slot, stringPtrValue(ref))
	return &status, err
}

// WorkspaceCreatePreflight is the resolver for the workspaceCreatePreflight field.
func (r *mutationResolver) WorkspaceCreatePreflight(ctx context.Context, input model.WorkspaceCreateInput) (*api.WorkspaceCreatePreflightResponse, error) {
	resp, err := r.Platform.WorkspaceCreatePreflight(ctx, workspaceCreateRequestFrom(input))
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// MintConnectionToken is the resolver for the mintConnectionToken field.
func (r *mutationResolver) MintConnectionToken(ctx context.Context, actor string, scope []string, ttl *string) (*api.ConnectionTokenResponse, error) {
	if r.Tokens == nil {
		return nil, errSubscriptionsUnavailable
	}
	resp, err := r.Tokens.MintConnection(actor, scope, stringPtrValue(ttl))
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// MintRouteToken is the resolver for the mintRouteToken field.
func (r *mutationResolver) MintRouteToken(ctx context.Context, actor string, service string, ttl *string) (*api.ConnectionTokenResponse, error) {
	if r.Tokens == nil {
		return nil, errSubscriptionsUnavailable
	}
	resp, err := r.Tokens.MintRoute(actor, service, stringPtrValue(ttl))
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// WorkspaceSourceMerge is the resolver for the workspaceSourceMerge field.
func (r *mutationResolver) WorkspaceSourceMerge(ctx context.Context, workspace string, slot string, ref string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceMerge(ctx, workspace, slot, ref)
	return &res, err
}

// WorkspaceSourceRebase is the resolver for the workspaceSourceRebase field.
func (r *mutationResolver) WorkspaceSourceRebase(ctx context.Context, workspace string, slot string, ref string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceRebase(ctx, workspace, slot, ref)
	return &res, err
}

// WorkspaceSourceMergeAbort is the resolver for the workspaceSourceMergeAbort field.
func (r *mutationResolver) WorkspaceSourceMergeAbort(ctx context.Context, workspace string, slot string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceMergeAbort(ctx, workspace, slot)
	return &res, err
}

// WorkspaceSourceRebaseAbort is the resolver for the workspaceSourceRebaseAbort field.
func (r *mutationResolver) WorkspaceSourceRebaseAbort(ctx context.Context, workspace string, slot string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceRebaseAbort(ctx, workspace, slot)
	return &res, err
}

// WorkspaceSourceRebaseContinue is the resolver for the workspaceSourceRebaseContinue field.
func (r *mutationResolver) WorkspaceSourceRebaseContinue(ctx context.Context, workspace string, slot string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourceRebaseContinue(ctx, workspace, slot)
	return &res, err
}

// WorkspaceSourcePublish is the resolver for the workspaceSourcePublish field.
func (r *mutationResolver) WorkspaceSourcePublish(ctx context.Context, workspace string, slot string, remote *string, branch *string) (*api.GitOpResult, error) {
	res, err := r.Platform.WorkspaceSourcePublish(ctx, workspace, slot, stringPtrValue(remote), stringPtrValue(branch))
	return &res, err
}

// CreateOneSecret is the resolver for the createOneSecret field.
func (r *mutationResolver) CreateOneSecret(ctx context.Context, input model.CreateOneSecretInput) (*api.SecretRef, error) {
	ref, err := r.Platform.SecretSet(ctx, input.Secret.Name, input.Secret.Value)
	if err != nil {
		return nil, err
	}
	return &ref, nil
}

// UpdateOneSecret is the resolver for the updateOneSecret field.
func (r *mutationResolver) UpdateOneSecret(ctx context.Context, input model.UpdateOneSecretInput) (*api.SecretRef, error) {
	ref, err := r.Platform.SecretSet(ctx, input.ID, input.Update.Value)
	if err != nil {
		return nil, err
	}
	return &ref, nil
}

// DeleteOneSecret is the resolver for the deleteOneSecret field.
func (r *mutationResolver) DeleteOneSecret(ctx context.Context, input model.DeleteOneSecretInput) (*api.SecretRef, error) {
	// SecretGet returns a zero-ish ref (not an error) for an unknown name, and
	// SecretDelete is idempotent — so guard for "exists" the way DeleteOneService
	// does, rather than reporting a fabricated delete of a secret that never was.
	prev, err := r.Platform.SecretGet(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	if !prev.Declared && !prev.HasValue && !prev.Required && !prev.Generated {
		return nil, fmt.Errorf("secret %q not found", input.ID)
	}
	if err := r.Platform.SecretDelete(ctx, input.ID); err != nil {
		return nil, err
	}
	return &prev, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.MutationResult, error) {
	return actionResult("ok"), nil
}

// StackStatus is the resolver for the stackStatus field.
func (r *queryResolver) StackStatus(ctx context.Context) (*api.StackStatusResponse, error) {
	status, err := r.Platform.StackStatus(ctx)
	return &status, err
}

// ServiceEndpoint is the resolver for the serviceEndpoint field.
func (r *queryResolver) ServiceEndpoint(ctx context.Context, name string) (*api.ServiceEndpoint, error) {
	return r.Platform.ServiceEndpoint(ctx, name)
}

// IngressStatus is the resolver for the ingressStatus field.
func (r *queryResolver) IngressStatus(ctx context.Context) (*api.IngressStatus, error) {
	return r.Platform.IngressStatus(ctx)
}

// Services is the resolver for the services field.
func (r *queryResolver) Services(ctx context.Context, filter *model.ServiceStateFilter, sorting []*model.ServiceStateSort, paging *model.OffsetPaging) (*model.ServiceStateConnection, error) {
	args := query.Args{Filter: bindServiceFilter(filter), Sorting: bindServiceSorts(sorting), Paging: bindPaging(paging)}
	page, total, err := r.Platform.ServiceList(ctx, args)
	if err != nil {
		return nil, err
	}
	return &model.ServiceStateConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Service is the resolver for the service field.
func (r *queryResolver) Service(ctx context.Context, id string) (*api.ServiceState, error) {
	return r.serviceByID(ctx, id)
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context, filter *model.JobStateFilter, sorting []*model.JobStateSort, paging *model.OffsetPaging) (*model.JobStateConnection, error) {
	args := query.Args{Filter: bindJobFilter(filter), Sorting: bindJobSorts(sorting), Paging: bindPaging(paging)}
	page, total, err := r.Platform.JobList(ctx, args)
	if err != nil {
		return nil, err
	}
	return &model.JobStateConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string) (*api.JobState, error) {
	return r.jobByID(ctx, id)
}

// Sources is the resolver for the sources field.
func (r *queryResolver) Sources(ctx context.Context, filter *model.SourceStateFilter, sorting []*model.SourceStateSort, paging *model.OffsetPaging) (*model.SourceStateConnection, error) {
	args := query.Args{Filter: bindSourceFilter(filter), Sorting: bindSourceSorts(sorting), Paging: bindPaging(paging)}
	page, total, err := r.Platform.SourceList(ctx, args)
	if err != nil {
		return nil, err
	}
	return &model.SourceStateConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Source is the resolver for the source field.
func (r *queryResolver) Source(ctx context.Context, id string) (*api.SourceState, error) {
	state, err := r.Platform.SourceStatus(ctx, id)
	return &state, err
}

// Workspaces is the resolver for the workspaces field.
func (r *queryResolver) Workspaces(ctx context.Context, filter *model.WorkspaceRefFilter, sorting []*model.WorkspaceRefSort, paging *model.OffsetPaging) (*model.WorkspaceRefConnection, error) {
	args := query.Args{Filter: bindWorkspaceFilter(filter), Sorting: bindWorkspaceSorts(sorting), Paging: bindPaging(paging)}
	page, total, err := r.Platform.WorkspaceList(ctx, args)
	if err != nil {
		return nil, err
	}
	return &model.WorkspaceRefConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context, id string) (*api.WorkspaceRef, error) {
	workspace, err := r.Platform.WorkspaceGet(ctx, id)
	return &workspace, err
}

// WorkspaceStatus is the resolver for the workspaceStatus field.
func (r *queryResolver) WorkspaceStatus(ctx context.Context, name string) (*api.WorkspaceStatusResponse, error) {
	status, err := r.Platform.WorkspaceStatus(ctx, name)
	return &status, err
}

// WorkspaceGit is the resolver for the workspaceGit field.
func (r *queryResolver) WorkspaceGit(ctx context.Context, name string) ([]*api.SourceState, error) {
	states, err := r.Platform.WorkspaceGitStatus(ctx, name)
	return ptrSlice(states), err
}

// GitOpsTopology is the resolver for the gitOpsTopology field.
func (r *queryResolver) GitOpsTopology(ctx context.Context, withCommits *int) (*api.GitOpsTopologyResponse, error) {
	limit := 0
	if withCommits != nil {
		limit = *withCommits
	}
	topology, err := r.Platform.GitOpsTopologyWithCommits(ctx, limit)
	return &topology, err
}

// SourceDiff is the resolver for the sourceDiff field.
func (r *queryResolver) SourceDiff(ctx context.Context, name string, ref *string) ([]*api.DiffFile, error) {
	files, err := r.Platform.SourceDiff(ctx, name, stringPtrValue(ref))
	if err != nil {
		return nil, err
	}
	out := make([]*api.DiffFile, len(files))
	for i := range files {
		out[i] = &files[i]
	}
	return out, nil
}

// WorkspaceSourceDiff is the resolver for the workspaceSourceDiff field.
func (r *queryResolver) WorkspaceSourceDiff(ctx context.Context, workspace string, slot string, ref *string) ([]*api.DiffFile, error) {
	files, err := r.Platform.WorkspaceSourceDiff(ctx, workspace, slot, stringPtrValue(ref))
	if err != nil {
		return nil, err
	}
	out := make([]*api.DiffFile, len(files))
	for i := range files {
		out[i] = &files[i]
	}
	return out, nil
}

// StackLogs is the resolver for the stackLogs field.
func (r *queryResolver) StackLogs(ctx context.Context, services []string, limit *int) (string, error) {
	maxBytes := logLimitValue(limit)
	logs, err := r.Platform.StackLogsLimited(ctx, services, false, maxBytes)
	if err != nil {
		return "", err
	}
	return collectLogStream(logs, maxBytes), nil
}

// ServiceLogs is the resolver for the serviceLogs field.
func (r *queryResolver) ServiceLogs(ctx context.Context, name string, limit *int) (string, error) {
	maxBytes := logLimitValue(limit)
	logs, err := r.Platform.StackLogsLimited(ctx, []string{name}, false, maxBytes)
	if err != nil {
		return "", err
	}
	return collectLogStream(logs, maxBytes), nil
}

// WorkspaceLogs is the resolver for the workspaceLogs field.
func (r *queryResolver) WorkspaceLogs(ctx context.Context, name string, limit *int) (string, error) {
	maxBytes := logLimitValue(limit)
	logs, err := r.Platform.WorkspaceLogsLimited(ctx, name, false, maxBytes)
	if err != nil {
		return "", err
	}
	return collectLogStream(logs, maxBytes), nil
}

// McpDescriptor is the resolver for the mcpDescriptor field.
func (r *queryResolver) McpDescriptor(ctx context.Context) (map[string]any, error) {
	return mcpDescriptor(), nil
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context, filter *model.TemplateDescriptorFilter, sorting []*model.TemplateDescriptorSort, paging *model.OffsetPaging) (*model.TemplateDescriptorConnection, error) {
	args := query.Args{Filter: bindTemplateFilter(filter), Sorting: bindTemplateSorts(sorting), Paging: bindPaging(paging)}
	page, total, err := r.Platform.Templates(ctx, args)
	if err != nil {
		return nil, err
	}
	return &model.TemplateDescriptorConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Template is the resolver for the template field.
func (r *queryResolver) Template(ctx context.Context, id string) (*api.TemplateDescriptor, error) {
	desc, err := r.Platform.Template(ctx, id)
	if err != nil {
		return nil, err
	}
	return &desc, nil
}

// Secrets is the resolver for the secrets field.
func (r *queryResolver) Secrets(ctx context.Context, filter *model.SecretRefFilter, sorting []*model.SecretRefSort, paging *model.OffsetPaging) (*model.SecretRefConnection, error) {
	args := query.Args{Filter: bindSecretFilter(filter), Sorting: bindSecretSorts(sorting), Paging: bindPaging(paging)}
	page, total, err := r.Platform.SecretsList(ctx, args)
	if err != nil {
		return nil, err
	}
	return &model.SecretRefConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Secret is the resolver for the secret field.
func (r *queryResolver) Secret(ctx context.Context, id string) (*api.SecretRef, error) {
	ref, err := r.Platform.SecretGet(ctx, id)
	if err != nil {
		return nil, err
	}
	return &ref, nil
}

// SecretValue is the resolver for the secretValue field.
func (r *queryResolver) SecretValue(ctx context.Context, name string) (*api.SecretValueResponse, error) {
	resp, err := r.Platform.SecretValue(ctx, name)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// ServiceAggregate is the resolver for the serviceAggregate field.
func (r *queryResolver) ServiceAggregate(ctx context.Context, filter *model.ServiceStateFilter, groupBy []model.ServiceStateGroupByFields) ([]*model.ServiceStateAggregateGroup, error) {
	items, _, err := r.Platform.ServiceList(ctx, query.Args{})
	if err != nil {
		return nil, err
	}
	groups := query.Aggregate(items, bindServiceFilter(filter), enumStrings(groupBy), queryfields.Service, nil, nil)
	out := make([]*model.ServiceStateAggregateGroup, len(groups))
	for i, g := range groups {
		out[i] = &model.ServiceStateAggregateGroup{
			Group: aggregateKeyValues(g.Key),
			Count: g.Count,
			Min:   numericKeyValues(g.Min),
			Max:   numericKeyValues(g.Max),
			Sum:   numericKeyValues(g.Sum),
		}
	}
	return out, nil
}

// SourceAggregate is the resolver for the sourceAggregate field.
func (r *queryResolver) SourceAggregate(ctx context.Context, filter *model.SourceStateFilter, groupBy []model.SourceStateGroupByFields) ([]*model.SourceStateAggregateGroup, error) {
	items, _, err := r.Platform.SourceList(ctx, query.Args{})
	if err != nil {
		return nil, err
	}
	groups := query.Aggregate(items, bindSourceFilter(filter), enumStrings(groupBy), queryfields.Source, queryfields.SourceNumeric, []string{"ahead", "behind"})
	out := make([]*model.SourceStateAggregateGroup, len(groups))
	for i, g := range groups {
		out[i] = &model.SourceStateAggregateGroup{
			Group: aggregateKeyValues(g.Key),
			Count: g.Count,
			Min:   numericKeyValues(g.Min),
			Max:   numericKeyValues(g.Max),
			Sum:   numericKeyValues(g.Sum),
		}
	}
	return out, nil
}

// ID is the resolver for the id field.
func (r *secretRefResolver) ID(ctx context.Context, obj *api.SecretRef) (string, error) {
	return obj.Name, nil
}

// ID is the resolver for the id field.
func (r *serviceStateResolver) ID(ctx context.Context, obj *api.ServiceState) (string, error) {
	return obj.Name, nil
}

// ID is the resolver for the id field.
func (r *sourceStateResolver) ID(ctx context.Context, obj *api.SourceState) (string, error) {
	return obj.Name, nil
}

// Services is the resolver for the services field.
func (r *stackStatusResolver) Services(ctx context.Context, obj *api.StackStatusResponse) ([]*api.ServiceState, error) {
	if obj == nil {
		return nil, nil
	}
	return ptrSlice(sortedMapValues(obj.Services)), nil
}

// Jobs is the resolver for the jobs field.
func (r *stackStatusResolver) Jobs(ctx context.Context, obj *api.StackStatusResponse) ([]*api.JobState, error) {
	if obj == nil {
		return nil, nil
	}
	return ptrSlice(sortedMapValues(obj.Jobs)), nil
}

// Workspaces is the resolver for the workspaces field.
func (r *stackStatusResolver) Workspaces(ctx context.Context, obj *api.StackStatusResponse) ([]*api.WorkspaceRef, error) {
	if obj == nil {
		return nil, nil
	}
	return ptrSlice(sortedMapValues(obj.Workspaces)), nil
}

// OnGitOpsTopologyChange is the resolver for the onGitOpsTopologyChange field.
func (r *subscriptionResolver) OnGitOpsTopologyChange(ctx context.Context) (<-chan *api.GitOpsTopologyResponse, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeTopology(ctx), nil
}

// OnServiceLogs is the resolver for the onServiceLogs field.
func (r *subscriptionResolver) OnServiceLogs(ctx context.Context, name string) (<-chan string, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeServiceLogs(ctx, name)
}

// OnWorkspaceLogs is the resolver for the onWorkspaceLogs field.
func (r *subscriptionResolver) OnWorkspaceLogs(ctx context.Context, name string) (<-chan string, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeWorkspaceLogs(ctx, name)
}

// OnWorkspaceStatusChange is the resolver for the onWorkspaceStatusChange field.
func (r *subscriptionResolver) OnWorkspaceStatusChange(ctx context.Context, name string) (<-chan *api.WorkspaceStatusResponse, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeWorkspaceStatus(ctx, name), nil
}

// OnStackSnapshotChange is the resolver for the onStackSnapshotChange field.
func (r *subscriptionResolver) OnStackSnapshotChange(ctx context.Context) (<-chan *model.StackSnapshot, error) {
	if r.Events == nil {
		return nil, errSubscriptionsUnavailable
	}
	return r.Events.SubscribeSnapshot(ctx), nil
}

// ID is the resolver for the id field.
func (r *templateDescriptorResolver) ID(ctx context.Context, obj *api.TemplateDescriptor) (string, error) {
	return obj.Ref, nil
}

// EffectiveInputs is the resolver for the effectiveInputs field.
func (r *workspaceCreatePreflightResolver) EffectiveInputs(ctx context.Context, obj *api.WorkspaceCreatePreflightResponse) ([]*model.KeyValue, error) {
	if obj == nil {
		return nil, nil
	}
	return keyValueList(obj.EffectiveInputs), nil
}

// ID is the resolver for the id field.
func (r *workspaceRefResolver) ID(ctx context.Context, obj *api.WorkspaceRef) (string, error) {
	return obj.Name, nil
}

// TTLExpiresAt is the resolver for the ttlExpiresAt field.
func (r *workspaceRefResolver) TTLExpiresAt(ctx context.Context, obj *api.WorkspaceRef) (*string, error) {
	if obj == nil {
		return nil, nil
	}
	return formatGraphQLTime(obj.TTLExpiresAt), nil
}

// ID is the resolver for the id field.
func (r *workspaceStatusResolver) ID(ctx context.Context, obj *api.WorkspaceStatusResponse) (string, error) {
	if obj == nil {
		return "", nil
	}
	return obj.Name, nil
}

// Inputs is the resolver for the inputs field.
func (r *workspaceStatusResolver) Inputs(ctx context.Context, obj *api.WorkspaceStatusResponse) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return stringMapJSON(obj.Inputs), nil
}

// Sources is the resolver for the sources field.
func (r *workspaceStatusResolver) Sources(ctx context.Context, obj *api.WorkspaceStatusResponse, filter *model.WorkspaceSourceStatusFilter, sorting []*model.WorkspaceSourceStatusSort, paging *model.OffsetPaging) (*model.WorkspaceSourceStatusConnection, error) {
	var items []api.WorkspaceSourceStatus
	if obj != nil {
		items = obj.Sources
	}
	args := query.Args{Filter: bindWorkspaceSourceStatusFilter(filter), Sorting: bindWorkspaceSourceStatusSorts(sorting), Paging: bindPaging(paging)}
	page, total := query.Apply(items, args, queryfields.WorkspaceSource)
	return &model.WorkspaceSourceStatusConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// Allocations is the resolver for the allocations field.
func (r *workspaceStatusResolver) Allocations(ctx context.Context, obj *api.WorkspaceStatusResponse) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return intMapJSON(obj.Allocations), nil
}

// PersistPaths is the resolver for the persistPaths field.
func (r *workspaceStatusResolver) PersistPaths(ctx context.Context, obj *api.WorkspaceStatusResponse) (map[string]any, error) {
	if obj == nil {
		return nil, nil
	}
	return anyMapJSON(obj.PersistPaths), nil
}

// TTLExpiresAt is the resolver for the ttlExpiresAt field.
func (r *workspaceStatusResolver) TTLExpiresAt(ctx context.Context, obj *api.WorkspaceStatusResponse) (*string, error) {
	if obj == nil {
		return nil, nil
	}
	return formatGraphQLTime(obj.TTLExpiresAt), nil
}

// MountedBy is the resolver for the mountedBy field.
func (r *workspaceStatusResolver) MountedBy(ctx context.Context, obj *api.WorkspaceStatusResponse, filter *model.WorkspaceMountRefFilter, sorting []*model.WorkspaceMountRefSort, paging *model.OffsetPaging) (*model.WorkspaceMountRefConnection, error) {
	var items []api.WorkspaceMountRef
	if obj != nil {
		items = obj.MountedBy
	}
	args := query.Args{Filter: bindWorkspaceMountRefFilter(filter), Sorting: bindWorkspaceMountRefSorts(sorting), Paging: bindPaging(paging)}
	page, total := query.Apply(items, args, queryfields.WorkspaceMount)
	return &model.WorkspaceMountRefConnection{Nodes: ptrSlice(page), TotalCount: total, PageInfo: offsetPageInfo(args.Paging, total, len(page))}, nil
}

// CompiledStack returns CompiledStackResolver implementation.
func (r *Resolver) CompiledStack() CompiledStackResolver { return &compiledStackResolver{r} }

// GitOpsTopology returns GitOpsTopologyResolver implementation.
func (r *Resolver) GitOpsTopology() GitOpsTopologyResolver { return &gitOpsTopologyResolver{r} }

// JobState returns JobStateResolver implementation.
func (r *Resolver) JobState() JobStateResolver { return &jobStateResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SecretRef returns SecretRefResolver implementation.
func (r *Resolver) SecretRef() SecretRefResolver { return &secretRefResolver{r} }

// ServiceState returns ServiceStateResolver implementation.
func (r *Resolver) ServiceState() ServiceStateResolver { return &serviceStateResolver{r} }

// SourceState returns SourceStateResolver implementation.
func (r *Resolver) SourceState() SourceStateResolver { return &sourceStateResolver{r} }

// StackStatus returns StackStatusResolver implementation.
func (r *Resolver) StackStatus() StackStatusResolver { return &stackStatusResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// TemplateDescriptor returns TemplateDescriptorResolver implementation.
func (r *Resolver) TemplateDescriptor() TemplateDescriptorResolver {
	return &templateDescriptorResolver{r}
}

// WorkspaceCreatePreflight returns WorkspaceCreatePreflightResolver implementation.
func (r *Resolver) WorkspaceCreatePreflight() WorkspaceCreatePreflightResolver {
	return &workspaceCreatePreflightResolver{r}
}

// WorkspaceRef returns WorkspaceRefResolver implementation.
func (r *Resolver) WorkspaceRef() WorkspaceRefResolver { return &workspaceRefResolver{r} }

// WorkspaceStatus returns WorkspaceStatusResolver implementation.
func (r *Resolver) WorkspaceStatus() WorkspaceStatusResolver { return &workspaceStatusResolver{r} }

type compiledStackResolver struct{ *Resolver }
type gitOpsTopologyResolver struct{ *Resolver }
type jobStateResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type secretRefResolver struct{ *Resolver }
type serviceStateResolver struct{ *Resolver }
type sourceStateResolver struct{ *Resolver }
type stackStatusResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type templateDescriptorResolver struct{ *Resolver }
type workspaceCreatePreflightResolver struct{ *Resolver }
type workspaceRefResolver struct{ *Resolver }
type workspaceStatusResolver struct{ *Resolver }
