// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/ang-ee/angee-operator/api"
)

type BooleanFieldComparison struct {
	Is    *bool `json:"is,omitempty"`
	IsNot *bool `json:"isNot,omitempty"`
}

type CreateOneSecretInput struct {
	Secret *SecretCreateInput `json:"secret"`
}

type CreateOneServiceInput struct {
	Service *ServiceCreateInput `json:"service"`
}

type CreateOneWorkspaceInput struct {
	Workspace *WorkspaceCreateInput `json:"workspace"`
}

type DeleteOneSecretInput struct {
	ID string `json:"id"`
}

type DeleteOneServiceInput struct {
	ID string `json:"id"`
}

type DeleteOneWorkspaceInput struct {
	ID    string `json:"id"`
	Purge *bool  `json:"purge,omitempty"`
}

type GitOpsLinkConnection struct {
	Nodes      []*api.GitOpsLink `json:"nodes"`
	TotalCount int               `json:"totalCount"`
	PageInfo   *OffsetPageInfo   `json:"pageInfo"`
}

type GitOpsLinkFilter struct {
	And       []*GitOpsLinkFilter     `json:"and,omitempty"`
	Or        []*GitOpsLinkFilter     `json:"or,omitempty"`
	ID        *StringFieldComparison  `json:"id,omitempty"`
	Source    *StringFieldComparison  `json:"source,omitempty"`
	Workspace *StringFieldComparison  `json:"workspace,omitempty"`
	Slot      *StringFieldComparison  `json:"slot,omitempty"`
	Kind      *StringFieldComparison  `json:"kind,omitempty"`
	Mode      *StringFieldComparison  `json:"mode,omitempty"`
	State     *StringFieldComparison  `json:"state,omitempty"`
	Branch    *StringFieldComparison  `json:"branch,omitempty"`
	Dirty     *BooleanFieldComparison `json:"dirty,omitempty"`
	Pushed    *BooleanFieldComparison `json:"pushed,omitempty"`
}

type GitOpsLinkSort struct {
	Field     GitOpsLinkSortFields `json:"field"`
	Direction SortDirection        `json:"direction"`
	Nulls     *SortNulls           `json:"nulls,omitempty"`
}

type JobStateConnection struct {
	Nodes      []*api.JobState `json:"nodes"`
	TotalCount int             `json:"totalCount"`
	PageInfo   *OffsetPageInfo `json:"pageInfo"`
}

type JobStateFilter struct {
	And     []*JobStateFilter      `json:"and,omitempty"`
	Or      []*JobStateFilter      `json:"or,omitempty"`
	ID      *StringFieldComparison `json:"id,omitempty"`
	Name    *StringFieldComparison `json:"name,omitempty"`
	Runtime *StringFieldComparison `json:"runtime,omitempty"`
}

type JobStateSort struct {
	Field     JobStateSortFields `json:"field"`
	Direction SortDirection      `json:"direction"`
	Nulls     *SortNulls         `json:"nulls,omitempty"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type MutationResult struct {
	Status  string  `json:"status"`
	Name    *string `json:"name,omitempty"`
	Message *string `json:"message,omitempty"`
}

type OffsetPageInfo struct {
	HasNextPage     *bool `json:"hasNextPage,omitempty"`
	HasPreviousPage *bool `json:"hasPreviousPage,omitempty"`
}

type OffsetPaging struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Query struct {
}

type SecretCreateInput struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type SecretRefConnection struct {
	Nodes      []*api.SecretRef `json:"nodes"`
	TotalCount int              `json:"totalCount"`
	PageInfo   *OffsetPageInfo  `json:"pageInfo"`
}

type SecretRefFilter struct {
	And       []*SecretRefFilter      `json:"and,omitempty"`
	Or        []*SecretRefFilter      `json:"or,omitempty"`
	ID        *StringFieldComparison  `json:"id,omitempty"`
	Name      *StringFieldComparison  `json:"name,omitempty"`
	EnvVar    *StringFieldComparison  `json:"envVar,omitempty"`
	Declared  *BooleanFieldComparison `json:"declared,omitempty"`
	HasValue  *BooleanFieldComparison `json:"hasValue,omitempty"`
	Required  *BooleanFieldComparison `json:"required,omitempty"`
	Generated *BooleanFieldComparison `json:"generated,omitempty"`
}

type SecretRefSort struct {
	Field     SecretRefSortFields `json:"field"`
	Direction SortDirection       `json:"direction"`
	Nulls     *SortNulls          `json:"nulls,omitempty"`
}

type SecretUpdateInput struct {
	Value string `json:"value"`
}

type ServiceCreateInput struct {
	Template  string           `json:"template"`
	Workspace string           `json:"workspace"`
	Inputs    []*KeyValueInput `json:"inputs,omitempty"`
	Name      *string          `json:"name,omitempty"`
	Start     *bool            `json:"start,omitempty"`
}

type ServiceInput struct {
	Name    *string          `json:"name,omitempty"`
	Runtime *string          `json:"runtime,omitempty"`
	Image   *string          `json:"image,omitempty"`
	Command []string         `json:"command,omitempty"`
	Mounts  []string         `json:"mounts,omitempty"`
	Env     []*KeyValueInput `json:"env,omitempty"`
	Ports   []string         `json:"ports,omitempty"`
	Workdir *string          `json:"workdir,omitempty"`
	Start   *bool            `json:"start,omitempty"`
}

type ServiceStateAggregateGroup struct {
	Group []*KeyValue `json:"group"`
	Count int         `json:"count"`
	Min   []*KeyValue `json:"min,omitempty"`
	Max   []*KeyValue `json:"max,omitempty"`
	Sum   []*KeyValue `json:"sum,omitempty"`
}

type ServiceStateConnection struct {
	Nodes      []*api.ServiceState `json:"nodes"`
	TotalCount int                 `json:"totalCount"`
	PageInfo   *OffsetPageInfo     `json:"pageInfo"`
}

type ServiceStateFilter struct {
	And     []*ServiceStateFilter  `json:"and,omitempty"`
	Or      []*ServiceStateFilter  `json:"or,omitempty"`
	ID      *StringFieldComparison `json:"id,omitempty"`
	Name    *StringFieldComparison `json:"name,omitempty"`
	Runtime *StringFieldComparison `json:"runtime,omitempty"`
	Status  *StringFieldComparison `json:"status,omitempty"`
	Health  *StringFieldComparison `json:"health,omitempty"`
}

type ServiceStateSort struct {
	Field     ServiceStateSortFields `json:"field"`
	Direction SortDirection          `json:"direction"`
	Nulls     *SortNulls             `json:"nulls,omitempty"`
}

type SourceStateAggregateGroup struct {
	Group []*KeyValue `json:"group"`
	Count int         `json:"count"`
	Min   []*KeyValue `json:"min,omitempty"`
	Max   []*KeyValue `json:"max,omitempty"`
	Sum   []*KeyValue `json:"sum,omitempty"`
}

type SourceStateConnection struct {
	Nodes      []*api.SourceState `json:"nodes"`
	TotalCount int                `json:"totalCount"`
	PageInfo   *OffsetPageInfo    `json:"pageInfo"`
}

type SourceStateFilter struct {
	And    []*SourceStateFilter    `json:"and,omitempty"`
	Or     []*SourceStateFilter    `json:"or,omitempty"`
	ID     *StringFieldComparison  `json:"id,omitempty"`
	Name   *StringFieldComparison  `json:"name,omitempty"`
	Kind   *StringFieldComparison  `json:"kind,omitempty"`
	State  *StringFieldComparison  `json:"state,omitempty"`
	Branch *StringFieldComparison  `json:"branch,omitempty"`
	Exists *BooleanFieldComparison `json:"exists,omitempty"`
	Dirty  *BooleanFieldComparison `json:"dirty,omitempty"`
	Pushed *BooleanFieldComparison `json:"pushed,omitempty"`
}

type SourceStateSort struct {
	Field     SourceStateSortFields `json:"field"`
	Direction SortDirection         `json:"direction"`
	Nulls     *SortNulls            `json:"nulls,omitempty"`
}

type StackInitInput struct {
	Template string           `json:"template"`
	Path     *string          `json:"path,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	Force    *bool            `json:"force,omitempty"`
}

type StackInitResult struct {
	Status   string `json:"status"`
	Template string `json:"template"`
	Root     string `json:"root"`
}

type StackRuntimeInput struct {
	Services []string `json:"services,omitempty"`
	Build    *bool    `json:"build,omitempty"`
}

// The stack overview aggregate — the root fields the web console reads as one.
// Mirrors the Query-root entity lists (as plain arrays, not connections) so a
// client can subscribe to the whole snapshot and field-prune via its selection set.
type StackSnapshot struct {
	Health         *MutationResult             `json:"health,omitempty"`
	StackStatus    *api.StackStatusResponse    `json:"stackStatus,omitempty"`
	Services       []*api.ServiceState         `json:"services"`
	Jobs           []*api.JobState             `json:"jobs"`
	Sources        []*api.SourceState          `json:"sources"`
	Workspaces     []*api.WorkspaceRef         `json:"workspaces"`
	Templates      []*api.TemplateDescriptor   `json:"templates"`
	Secrets        []*api.SecretRef            `json:"secrets"`
	GitOpsTopology *api.GitOpsTopologyResponse `json:"gitOpsTopology,omitempty"`
}

type StringFieldComparison struct {
	Is       *bool    `json:"is,omitempty"`
	IsNot    *bool    `json:"isNot,omitempty"`
	Eq       *string  `json:"eq,omitempty"`
	Neq      *string  `json:"neq,omitempty"`
	Gt       *string  `json:"gt,omitempty"`
	Gte      *string  `json:"gte,omitempty"`
	Lt       *string  `json:"lt,omitempty"`
	Lte      *string  `json:"lte,omitempty"`
	Like     *string  `json:"like,omitempty"`
	NotLike  *string  `json:"notLike,omitempty"`
	ILike    *string  `json:"iLike,omitempty"`
	NotILike *string  `json:"notILike,omitempty"`
	In       []string `json:"in,omitempty"`
	NotIn    []string `json:"notIn,omitempty"`
}

type Subscription struct {
}

type TemplateDescriptorConnection struct {
	Nodes      []*api.TemplateDescriptor `json:"nodes"`
	TotalCount int                       `json:"totalCount"`
	PageInfo   *OffsetPageInfo           `json:"pageInfo"`
}

type TemplateDescriptorFilter struct {
	And  []*TemplateDescriptorFilter `json:"and,omitempty"`
	Or   []*TemplateDescriptorFilter `json:"or,omitempty"`
	ID   *StringFieldComparison      `json:"id,omitempty"`
	Ref  *StringFieldComparison      `json:"ref,omitempty"`
	Kind *StringFieldComparison      `json:"kind,omitempty"`
	Name *StringFieldComparison      `json:"name,omitempty"`
}

type TemplateDescriptorSort struct {
	Field     TemplateDescriptorSortFields `json:"field"`
	Direction SortDirection                `json:"direction"`
	Nulls     *SortNulls                   `json:"nulls,omitempty"`
}

type UpdateOneSecretInput struct {
	ID     string             `json:"id"`
	Update *SecretUpdateInput `json:"update"`
}

type UpdateOneServiceInput struct {
	ID     string        `json:"id"`
	Update *ServiceInput `json:"update"`
}

type UpdateOneWorkspaceInput struct {
	ID     string                `json:"id"`
	Update *WorkspaceUpdateInput `json:"update"`
}

type WorkspaceCreateInput struct {
	Template string           `json:"template"`
	Name     *string          `json:"name,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	TTL      *string          `json:"ttl,omitempty"`
}

type WorkspaceMountRefConnection struct {
	Nodes      []*api.WorkspaceMountRef `json:"nodes"`
	TotalCount int                      `json:"totalCount"`
	PageInfo   *OffsetPageInfo          `json:"pageInfo"`
}

type WorkspaceMountRefFilter struct {
	And   []*WorkspaceMountRefFilter `json:"and,omitempty"`
	Or    []*WorkspaceMountRefFilter `json:"or,omitempty"`
	Kind  *StringFieldComparison     `json:"kind,omitempty"`
	Name  *StringFieldComparison     `json:"name,omitempty"`
	Field *StringFieldComparison     `json:"field,omitempty"`
	Value *StringFieldComparison     `json:"value,omitempty"`
}

type WorkspaceMountRefSort struct {
	Field     WorkspaceMountRefSortFields `json:"field"`
	Direction SortDirection               `json:"direction"`
	Nulls     *SortNulls                  `json:"nulls,omitempty"`
}

type WorkspaceRefConnection struct {
	Nodes      []*api.WorkspaceRef `json:"nodes"`
	TotalCount int                 `json:"totalCount"`
	PageInfo   *OffsetPageInfo     `json:"pageInfo"`
}

type WorkspaceRefFilter struct {
	And      []*WorkspaceRefFilter  `json:"and,omitempty"`
	Or       []*WorkspaceRefFilter  `json:"or,omitempty"`
	ID       *StringFieldComparison `json:"id,omitempty"`
	Name     *StringFieldComparison `json:"name,omitempty"`
	Template *StringFieldComparison `json:"template,omitempty"`
}

type WorkspaceRefSort struct {
	Field     WorkspaceRefSortFields `json:"field"`
	Direction SortDirection          `json:"direction"`
	Nulls     *SortNulls             `json:"nulls,omitempty"`
}

type WorkspaceSourceStatusConnection struct {
	Nodes      []*api.WorkspaceSourceStatus `json:"nodes"`
	TotalCount int                          `json:"totalCount"`
	PageInfo   *OffsetPageInfo              `json:"pageInfo"`
}

type WorkspaceSourceStatusFilter struct {
	And    []*WorkspaceSourceStatusFilter `json:"and,omitempty"`
	Or     []*WorkspaceSourceStatusFilter `json:"or,omitempty"`
	Slot   *StringFieldComparison         `json:"slot,omitempty"`
	Source *StringFieldComparison         `json:"source,omitempty"`
	Kind   *StringFieldComparison         `json:"kind,omitempty"`
	Mode   *StringFieldComparison         `json:"mode,omitempty"`
	State  *StringFieldComparison         `json:"state,omitempty"`
	Branch *StringFieldComparison         `json:"branch,omitempty"`
	Dirty  *BooleanFieldComparison        `json:"dirty,omitempty"`
	Pushed *BooleanFieldComparison        `json:"pushed,omitempty"`
	Exists *BooleanFieldComparison        `json:"exists,omitempty"`
}

type WorkspaceSourceStatusSort struct {
	Field     WorkspaceSourceStatusSortFields `json:"field"`
	Direction SortDirection                   `json:"direction"`
	Nulls     *SortNulls                      `json:"nulls,omitempty"`
}

type WorkspaceStatusConnection struct {
	Nodes      []*api.WorkspaceStatusResponse `json:"nodes"`
	TotalCount int                            `json:"totalCount"`
	PageInfo   *OffsetPageInfo                `json:"pageInfo"`
}

type WorkspaceStatusFilter struct {
	And      []*WorkspaceStatusFilter `json:"and,omitempty"`
	Or       []*WorkspaceStatusFilter `json:"or,omitempty"`
	ID       *StringFieldComparison   `json:"id,omitempty"`
	Name     *StringFieldComparison   `json:"name,omitempty"`
	State    *StringFieldComparison   `json:"state,omitempty"`
	Template *StringFieldComparison   `json:"template,omitempty"`
	Exists   *BooleanFieldComparison  `json:"exists,omitempty"`
	Expired  *BooleanFieldComparison  `json:"expired,omitempty"`
}

type WorkspaceStatusSort struct {
	Field     WorkspaceStatusSortFields `json:"field"`
	Direction SortDirection             `json:"direction"`
	Nulls     *SortNulls                `json:"nulls,omitempty"`
}

type WorkspaceUpdateInput struct {
	Inputs []*KeyValueInput `json:"inputs,omitempty"`
	TTL    *string          `json:"ttl,omitempty"`
}

type GitOpsLinkSortFields string

const (
	GitOpsLinkSortFieldsID        GitOpsLinkSortFields = "id"
	GitOpsLinkSortFieldsSource    GitOpsLinkSortFields = "source"
	GitOpsLinkSortFieldsWorkspace GitOpsLinkSortFields = "workspace"
	GitOpsLinkSortFieldsSlot      GitOpsLinkSortFields = "slot"
	GitOpsLinkSortFieldsKind      GitOpsLinkSortFields = "kind"
	GitOpsLinkSortFieldsMode      GitOpsLinkSortFields = "mode"
	GitOpsLinkSortFieldsState     GitOpsLinkSortFields = "state"
	GitOpsLinkSortFieldsBranch    GitOpsLinkSortFields = "branch"
)

var AllGitOpsLinkSortFields = []GitOpsLinkSortFields{
	GitOpsLinkSortFieldsID,
	GitOpsLinkSortFieldsSource,
	GitOpsLinkSortFieldsWorkspace,
	GitOpsLinkSortFieldsSlot,
	GitOpsLinkSortFieldsKind,
	GitOpsLinkSortFieldsMode,
	GitOpsLinkSortFieldsState,
	GitOpsLinkSortFieldsBranch,
}

func (e GitOpsLinkSortFields) IsValid() bool {
	switch e {
	case GitOpsLinkSortFieldsID, GitOpsLinkSortFieldsSource, GitOpsLinkSortFieldsWorkspace, GitOpsLinkSortFieldsSlot, GitOpsLinkSortFieldsKind, GitOpsLinkSortFieldsMode, GitOpsLinkSortFieldsState, GitOpsLinkSortFieldsBranch:
		return true
	}
	return false
}

func (e GitOpsLinkSortFields) String() string {
	return string(e)
}

func (e *GitOpsLinkSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GitOpsLinkSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GitOpsLinkSortFields", str)
	}
	return nil
}

func (e GitOpsLinkSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GitOpsLinkSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GitOpsLinkSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type JobStateSortFields string

const (
	JobStateSortFieldsID      JobStateSortFields = "id"
	JobStateSortFieldsName    JobStateSortFields = "name"
	JobStateSortFieldsRuntime JobStateSortFields = "runtime"
)

var AllJobStateSortFields = []JobStateSortFields{
	JobStateSortFieldsID,
	JobStateSortFieldsName,
	JobStateSortFieldsRuntime,
}

func (e JobStateSortFields) IsValid() bool {
	switch e {
	case JobStateSortFieldsID, JobStateSortFieldsName, JobStateSortFieldsRuntime:
		return true
	}
	return false
}

func (e JobStateSortFields) String() string {
	return string(e)
}

func (e *JobStateSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = JobStateSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid JobStateSortFields", str)
	}
	return nil
}

func (e JobStateSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *JobStateSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e JobStateSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SecretRefSortFields string

const (
	SecretRefSortFieldsID       SecretRefSortFields = "id"
	SecretRefSortFieldsName     SecretRefSortFields = "name"
	SecretRefSortFieldsEnvVar   SecretRefSortFields = "envVar"
	SecretRefSortFieldsDeclared SecretRefSortFields = "declared"
	SecretRefSortFieldsHasValue SecretRefSortFields = "hasValue"
)

var AllSecretRefSortFields = []SecretRefSortFields{
	SecretRefSortFieldsID,
	SecretRefSortFieldsName,
	SecretRefSortFieldsEnvVar,
	SecretRefSortFieldsDeclared,
	SecretRefSortFieldsHasValue,
}

func (e SecretRefSortFields) IsValid() bool {
	switch e {
	case SecretRefSortFieldsID, SecretRefSortFieldsName, SecretRefSortFieldsEnvVar, SecretRefSortFieldsDeclared, SecretRefSortFieldsHasValue:
		return true
	}
	return false
}

func (e SecretRefSortFields) String() string {
	return string(e)
}

func (e *SecretRefSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SecretRefSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SecretRefSortFields", str)
	}
	return nil
}

func (e SecretRefSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SecretRefSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SecretRefSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceStateGroupByFields string

const (
	ServiceStateGroupByFieldsStatus  ServiceStateGroupByFields = "status"
	ServiceStateGroupByFieldsRuntime ServiceStateGroupByFields = "runtime"
	ServiceStateGroupByFieldsHealth  ServiceStateGroupByFields = "health"
)

var AllServiceStateGroupByFields = []ServiceStateGroupByFields{
	ServiceStateGroupByFieldsStatus,
	ServiceStateGroupByFieldsRuntime,
	ServiceStateGroupByFieldsHealth,
}

func (e ServiceStateGroupByFields) IsValid() bool {
	switch e {
	case ServiceStateGroupByFieldsStatus, ServiceStateGroupByFieldsRuntime, ServiceStateGroupByFieldsHealth:
		return true
	}
	return false
}

func (e ServiceStateGroupByFields) String() string {
	return string(e)
}

func (e *ServiceStateGroupByFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceStateGroupByFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceStateGroupByFields", str)
	}
	return nil
}

func (e ServiceStateGroupByFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceStateGroupByFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceStateGroupByFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceStateSortFields string

const (
	ServiceStateSortFieldsID      ServiceStateSortFields = "id"
	ServiceStateSortFieldsName    ServiceStateSortFields = "name"
	ServiceStateSortFieldsRuntime ServiceStateSortFields = "runtime"
	ServiceStateSortFieldsStatus  ServiceStateSortFields = "status"
	ServiceStateSortFieldsHealth  ServiceStateSortFields = "health"
)

var AllServiceStateSortFields = []ServiceStateSortFields{
	ServiceStateSortFieldsID,
	ServiceStateSortFieldsName,
	ServiceStateSortFieldsRuntime,
	ServiceStateSortFieldsStatus,
	ServiceStateSortFieldsHealth,
}

func (e ServiceStateSortFields) IsValid() bool {
	switch e {
	case ServiceStateSortFieldsID, ServiceStateSortFieldsName, ServiceStateSortFieldsRuntime, ServiceStateSortFieldsStatus, ServiceStateSortFieldsHealth:
		return true
	}
	return false
}

func (e ServiceStateSortFields) String() string {
	return string(e)
}

func (e *ServiceStateSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceStateSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceStateSortFields", str)
	}
	return nil
}

func (e ServiceStateSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceStateSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceStateSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortNulls string

const (
	SortNullsNullsFirst SortNulls = "NULLS_FIRST"
	SortNullsNullsLast  SortNulls = "NULLS_LAST"
)

var AllSortNulls = []SortNulls{
	SortNullsNullsFirst,
	SortNullsNullsLast,
}

func (e SortNulls) IsValid() bool {
	switch e {
	case SortNullsNullsFirst, SortNullsNullsLast:
		return true
	}
	return false
}

func (e SortNulls) String() string {
	return string(e)
}

func (e *SortNulls) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortNulls(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortNulls", str)
	}
	return nil
}

func (e SortNulls) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortNulls) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortNulls) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SourceStateGroupByFields string

const (
	SourceStateGroupByFieldsKind   SourceStateGroupByFields = "kind"
	SourceStateGroupByFieldsState  SourceStateGroupByFields = "state"
	SourceStateGroupByFieldsBranch SourceStateGroupByFields = "branch"
	SourceStateGroupByFieldsDirty  SourceStateGroupByFields = "dirty"
	SourceStateGroupByFieldsPushed SourceStateGroupByFields = "pushed"
)

var AllSourceStateGroupByFields = []SourceStateGroupByFields{
	SourceStateGroupByFieldsKind,
	SourceStateGroupByFieldsState,
	SourceStateGroupByFieldsBranch,
	SourceStateGroupByFieldsDirty,
	SourceStateGroupByFieldsPushed,
}

func (e SourceStateGroupByFields) IsValid() bool {
	switch e {
	case SourceStateGroupByFieldsKind, SourceStateGroupByFieldsState, SourceStateGroupByFieldsBranch, SourceStateGroupByFieldsDirty, SourceStateGroupByFieldsPushed:
		return true
	}
	return false
}

func (e SourceStateGroupByFields) String() string {
	return string(e)
}

func (e *SourceStateGroupByFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SourceStateGroupByFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SourceStateGroupByFields", str)
	}
	return nil
}

func (e SourceStateGroupByFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SourceStateGroupByFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SourceStateGroupByFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SourceStateSortFields string

const (
	SourceStateSortFieldsID     SourceStateSortFields = "id"
	SourceStateSortFieldsName   SourceStateSortFields = "name"
	SourceStateSortFieldsKind   SourceStateSortFields = "kind"
	SourceStateSortFieldsState  SourceStateSortFields = "state"
	SourceStateSortFieldsBranch SourceStateSortFields = "branch"
)

var AllSourceStateSortFields = []SourceStateSortFields{
	SourceStateSortFieldsID,
	SourceStateSortFieldsName,
	SourceStateSortFieldsKind,
	SourceStateSortFieldsState,
	SourceStateSortFieldsBranch,
}

func (e SourceStateSortFields) IsValid() bool {
	switch e {
	case SourceStateSortFieldsID, SourceStateSortFieldsName, SourceStateSortFieldsKind, SourceStateSortFieldsState, SourceStateSortFieldsBranch:
		return true
	}
	return false
}

func (e SourceStateSortFields) String() string {
	return string(e)
}

func (e *SourceStateSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SourceStateSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SourceStateSortFields", str)
	}
	return nil
}

func (e SourceStateSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SourceStateSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SourceStateSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TemplateDescriptorSortFields string

const (
	TemplateDescriptorSortFieldsID   TemplateDescriptorSortFields = "id"
	TemplateDescriptorSortFieldsRef  TemplateDescriptorSortFields = "ref"
	TemplateDescriptorSortFieldsKind TemplateDescriptorSortFields = "kind"
	TemplateDescriptorSortFieldsName TemplateDescriptorSortFields = "name"
)

var AllTemplateDescriptorSortFields = []TemplateDescriptorSortFields{
	TemplateDescriptorSortFieldsID,
	TemplateDescriptorSortFieldsRef,
	TemplateDescriptorSortFieldsKind,
	TemplateDescriptorSortFieldsName,
}

func (e TemplateDescriptorSortFields) IsValid() bool {
	switch e {
	case TemplateDescriptorSortFieldsID, TemplateDescriptorSortFieldsRef, TemplateDescriptorSortFieldsKind, TemplateDescriptorSortFieldsName:
		return true
	}
	return false
}

func (e TemplateDescriptorSortFields) String() string {
	return string(e)
}

func (e *TemplateDescriptorSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TemplateDescriptorSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TemplateDescriptorSortFields", str)
	}
	return nil
}

func (e TemplateDescriptorSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TemplateDescriptorSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TemplateDescriptorSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceMountRefSortFields string

const (
	WorkspaceMountRefSortFieldsKind  WorkspaceMountRefSortFields = "kind"
	WorkspaceMountRefSortFieldsName  WorkspaceMountRefSortFields = "name"
	WorkspaceMountRefSortFieldsField WorkspaceMountRefSortFields = "field"
	WorkspaceMountRefSortFieldsValue WorkspaceMountRefSortFields = "value"
)

var AllWorkspaceMountRefSortFields = []WorkspaceMountRefSortFields{
	WorkspaceMountRefSortFieldsKind,
	WorkspaceMountRefSortFieldsName,
	WorkspaceMountRefSortFieldsField,
	WorkspaceMountRefSortFieldsValue,
}

func (e WorkspaceMountRefSortFields) IsValid() bool {
	switch e {
	case WorkspaceMountRefSortFieldsKind, WorkspaceMountRefSortFieldsName, WorkspaceMountRefSortFieldsField, WorkspaceMountRefSortFieldsValue:
		return true
	}
	return false
}

func (e WorkspaceMountRefSortFields) String() string {
	return string(e)
}

func (e *WorkspaceMountRefSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceMountRefSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceMountRefSortFields", str)
	}
	return nil
}

func (e WorkspaceMountRefSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceMountRefSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceMountRefSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceRefSortFields string

const (
	WorkspaceRefSortFieldsID       WorkspaceRefSortFields = "id"
	WorkspaceRefSortFieldsName     WorkspaceRefSortFields = "name"
	WorkspaceRefSortFieldsTemplate WorkspaceRefSortFields = "template"
)

var AllWorkspaceRefSortFields = []WorkspaceRefSortFields{
	WorkspaceRefSortFieldsID,
	WorkspaceRefSortFieldsName,
	WorkspaceRefSortFieldsTemplate,
}

func (e WorkspaceRefSortFields) IsValid() bool {
	switch e {
	case WorkspaceRefSortFieldsID, WorkspaceRefSortFieldsName, WorkspaceRefSortFieldsTemplate:
		return true
	}
	return false
}

func (e WorkspaceRefSortFields) String() string {
	return string(e)
}

func (e *WorkspaceRefSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceRefSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceRefSortFields", str)
	}
	return nil
}

func (e WorkspaceRefSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceRefSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceRefSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceSourceStatusSortFields string

const (
	WorkspaceSourceStatusSortFieldsSlot   WorkspaceSourceStatusSortFields = "slot"
	WorkspaceSourceStatusSortFieldsSource WorkspaceSourceStatusSortFields = "source"
	WorkspaceSourceStatusSortFieldsKind   WorkspaceSourceStatusSortFields = "kind"
	WorkspaceSourceStatusSortFieldsMode   WorkspaceSourceStatusSortFields = "mode"
	WorkspaceSourceStatusSortFieldsState  WorkspaceSourceStatusSortFields = "state"
	WorkspaceSourceStatusSortFieldsBranch WorkspaceSourceStatusSortFields = "branch"
)

var AllWorkspaceSourceStatusSortFields = []WorkspaceSourceStatusSortFields{
	WorkspaceSourceStatusSortFieldsSlot,
	WorkspaceSourceStatusSortFieldsSource,
	WorkspaceSourceStatusSortFieldsKind,
	WorkspaceSourceStatusSortFieldsMode,
	WorkspaceSourceStatusSortFieldsState,
	WorkspaceSourceStatusSortFieldsBranch,
}

func (e WorkspaceSourceStatusSortFields) IsValid() bool {
	switch e {
	case WorkspaceSourceStatusSortFieldsSlot, WorkspaceSourceStatusSortFieldsSource, WorkspaceSourceStatusSortFieldsKind, WorkspaceSourceStatusSortFieldsMode, WorkspaceSourceStatusSortFieldsState, WorkspaceSourceStatusSortFieldsBranch:
		return true
	}
	return false
}

func (e WorkspaceSourceStatusSortFields) String() string {
	return string(e)
}

func (e *WorkspaceSourceStatusSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceSourceStatusSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceSourceStatusSortFields", str)
	}
	return nil
}

func (e WorkspaceSourceStatusSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceSourceStatusSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceSourceStatusSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkspaceStatusSortFields string

const (
	WorkspaceStatusSortFieldsID       WorkspaceStatusSortFields = "id"
	WorkspaceStatusSortFieldsName     WorkspaceStatusSortFields = "name"
	WorkspaceStatusSortFieldsState    WorkspaceStatusSortFields = "state"
	WorkspaceStatusSortFieldsTemplate WorkspaceStatusSortFields = "template"
)

var AllWorkspaceStatusSortFields = []WorkspaceStatusSortFields{
	WorkspaceStatusSortFieldsID,
	WorkspaceStatusSortFieldsName,
	WorkspaceStatusSortFieldsState,
	WorkspaceStatusSortFieldsTemplate,
}

func (e WorkspaceStatusSortFields) IsValid() bool {
	switch e {
	case WorkspaceStatusSortFieldsID, WorkspaceStatusSortFieldsName, WorkspaceStatusSortFieldsState, WorkspaceStatusSortFieldsTemplate:
		return true
	}
	return false
}

func (e WorkspaceStatusSortFields) String() string {
	return string(e)
}

func (e *WorkspaceStatusSortFields) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkspaceStatusSortFields(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkspaceStatusSortFields", str)
	}
	return nil
}

func (e WorkspaceStatusSortFields) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkspaceStatusSortFields) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkspaceStatusSortFields) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
