// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/ang-ee/angee-operator/api"
)

type BooleanComparisonExp struct {
	Eq     *bool  `json:"_eq,omitempty"`
	Neq    *bool  `json:"_neq,omitempty"`
	In     []bool `json:"_in,omitempty"`
	Nin    []bool `json:"_nin,omitempty"`
	IsNull *bool  `json:"_is_null,omitempty"`
}

type IntComparisonExp struct {
	Eq     *int  `json:"_eq,omitempty"`
	Neq    *int  `json:"_neq,omitempty"`
	Gt     *int  `json:"_gt,omitempty"`
	Gte    *int  `json:"_gte,omitempty"`
	Lt     *int  `json:"_lt,omitempty"`
	Lte    *int  `json:"_lte,omitempty"`
	In     []int `json:"_in,omitempty"`
	Nin    []int `json:"_nin,omitempty"`
	IsNull *bool `json:"_is_null,omitempty"`
}

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type MutationResult struct {
	Status  string  `json:"status"`
	Name    *string `json:"name,omitempty"`
	Message *string `json:"message,omitempty"`
}

type Query struct {
}

type ServiceInput struct {
	Name    *string          `json:"name,omitempty"`
	Runtime *string          `json:"runtime,omitempty"`
	Image   *string          `json:"image,omitempty"`
	Command []string         `json:"command,omitempty"`
	Mounts  []string         `json:"mounts,omitempty"`
	Env     []*KeyValueInput `json:"env,omitempty"`
	Ports   []string         `json:"ports,omitempty"`
	Workdir *string          `json:"workdir,omitempty"`
	Start   *bool            `json:"start,omitempty"`
}

type ServicesGroupBySpec struct {
	Field       ServicesGroupableField `json:"field"`
	Granularity *Granularity           `json:"granularity,omitempty"`
}

type ServicesGroupKey struct {
	Status  *string `json:"status,omitempty"`
	Runtime *string `json:"runtime,omitempty"`
	Health  *string `json:"health,omitempty"`
}

type ServicesGroupOrder struct {
	Field     string   `json:"field"`
	Direction *OrderBy `json:"direction,omitempty"`
}

type ServicesHaving struct {
	CountGt    *int  `json:"count_gt,omitempty"`
	CountLt    *int  `json:"count_lt,omitempty"`
	CountLte   *int  `json:"count_lte,omitempty"`
	CountGte   *int  `json:"count_gte,omitempty"`
	CountEq    *int  `json:"count_eq,omitempty"`
	CountNeq   *int  `json:"count_neq,omitempty"`
	CountIn    []int `json:"count_in,omitempty"`
	CountNotIn []int `json:"count_not_in,omitempty"`
}

type SourcesGroupBySpec struct {
	Field       SourcesGroupableField `json:"field"`
	Granularity *Granularity          `json:"granularity,omitempty"`
}

type SourcesGroupKey struct {
	Kind   *string `json:"kind,omitempty"`
	State  *string `json:"state,omitempty"`
	Branch *string `json:"branch,omitempty"`
	Dirty  *bool   `json:"dirty,omitempty"`
	Pushed *bool   `json:"pushed,omitempty"`
}

type SourcesGroupOrder struct {
	Field     string   `json:"field"`
	Direction *OrderBy `json:"direction,omitempty"`
}

type SourcesHaving struct {
	CountGt        *int      `json:"count_gt,omitempty"`
	CountLt        *int      `json:"count_lt,omitempty"`
	CountLte       *int      `json:"count_lte,omitempty"`
	CountGte       *int      `json:"count_gte,omitempty"`
	CountEq        *int      `json:"count_eq,omitempty"`
	CountNeq       *int      `json:"count_neq,omitempty"`
	CountIn        []int     `json:"count_in,omitempty"`
	CountNotIn     []int     `json:"count_not_in,omitempty"`
	SumAheadGt     *int      `json:"sum_ahead_gt,omitempty"`
	SumAheadLt     *int      `json:"sum_ahead_lt,omitempty"`
	SumAheadLte    *int      `json:"sum_ahead_lte,omitempty"`
	SumAheadGte    *int      `json:"sum_ahead_gte,omitempty"`
	SumAheadEq     *int      `json:"sum_ahead_eq,omitempty"`
	SumAheadNeq    *int      `json:"sum_ahead_neq,omitempty"`
	SumAheadIn     []int     `json:"sum_ahead_in,omitempty"`
	SumAheadNotIn  []int     `json:"sum_ahead_not_in,omitempty"`
	SumBehindGt    *int      `json:"sum_behind_gt,omitempty"`
	SumBehindLt    *int      `json:"sum_behind_lt,omitempty"`
	SumBehindLte   *int      `json:"sum_behind_lte,omitempty"`
	SumBehindGte   *int      `json:"sum_behind_gte,omitempty"`
	SumBehindEq    *int      `json:"sum_behind_eq,omitempty"`
	SumBehindNeq   *int      `json:"sum_behind_neq,omitempty"`
	SumBehindIn    []int     `json:"sum_behind_in,omitempty"`
	SumBehindNotIn []int     `json:"sum_behind_not_in,omitempty"`
	AvgAheadGt     *float64  `json:"avg_ahead_gt,omitempty"`
	AvgAheadLt     *float64  `json:"avg_ahead_lt,omitempty"`
	AvgAheadLte    *float64  `json:"avg_ahead_lte,omitempty"`
	AvgAheadGte    *float64  `json:"avg_ahead_gte,omitempty"`
	AvgAheadEq     *float64  `json:"avg_ahead_eq,omitempty"`
	AvgAheadNeq    *float64  `json:"avg_ahead_neq,omitempty"`
	AvgAheadIn     []float64 `json:"avg_ahead_in,omitempty"`
	AvgAheadNotIn  []float64 `json:"avg_ahead_not_in,omitempty"`
	AvgBehindGt    *float64  `json:"avg_behind_gt,omitempty"`
	AvgBehindLt    *float64  `json:"avg_behind_lt,omitempty"`
	AvgBehindLte   *float64  `json:"avg_behind_lte,omitempty"`
	AvgBehindGte   *float64  `json:"avg_behind_gte,omitempty"`
	AvgBehindEq    *float64  `json:"avg_behind_eq,omitempty"`
	AvgBehindNeq   *float64  `json:"avg_behind_neq,omitempty"`
	AvgBehindIn    []float64 `json:"avg_behind_in,omitempty"`
	AvgBehindNotIn []float64 `json:"avg_behind_not_in,omitempty"`
	MinAheadGt     *int      `json:"min_ahead_gt,omitempty"`
	MinAheadLt     *int      `json:"min_ahead_lt,omitempty"`
	MinAheadLte    *int      `json:"min_ahead_lte,omitempty"`
	MinAheadGte    *int      `json:"min_ahead_gte,omitempty"`
	MinAheadEq     *int      `json:"min_ahead_eq,omitempty"`
	MinAheadNeq    *int      `json:"min_ahead_neq,omitempty"`
	MinAheadIn     []int     `json:"min_ahead_in,omitempty"`
	MinAheadNotIn  []int     `json:"min_ahead_not_in,omitempty"`
	MinBehindGt    *int      `json:"min_behind_gt,omitempty"`
	MinBehindLt    *int      `json:"min_behind_lt,omitempty"`
	MinBehindLte   *int      `json:"min_behind_lte,omitempty"`
	MinBehindGte   *int      `json:"min_behind_gte,omitempty"`
	MinBehindEq    *int      `json:"min_behind_eq,omitempty"`
	MinBehindNeq   *int      `json:"min_behind_neq,omitempty"`
	MinBehindIn    []int     `json:"min_behind_in,omitempty"`
	MinBehindNotIn []int     `json:"min_behind_not_in,omitempty"`
	MaxAheadGt     *int      `json:"max_ahead_gt,omitempty"`
	MaxAheadLt     *int      `json:"max_ahead_lt,omitempty"`
	MaxAheadLte    *int      `json:"max_ahead_lte,omitempty"`
	MaxAheadGte    *int      `json:"max_ahead_gte,omitempty"`
	MaxAheadEq     *int      `json:"max_ahead_eq,omitempty"`
	MaxAheadNeq    *int      `json:"max_ahead_neq,omitempty"`
	MaxAheadIn     []int     `json:"max_ahead_in,omitempty"`
	MaxAheadNotIn  []int     `json:"max_ahead_not_in,omitempty"`
	MaxBehindGt    *int      `json:"max_behind_gt,omitempty"`
	MaxBehindLt    *int      `json:"max_behind_lt,omitempty"`
	MaxBehindLte   *int      `json:"max_behind_lte,omitempty"`
	MaxBehindGte   *int      `json:"max_behind_gte,omitempty"`
	MaxBehindEq    *int      `json:"max_behind_eq,omitempty"`
	MaxBehindNeq   *int      `json:"max_behind_neq,omitempty"`
	MaxBehindIn    []int     `json:"max_behind_in,omitempty"`
	MaxBehindNotIn []int     `json:"max_behind_not_in,omitempty"`
}

type StackInitInput struct {
	Template string           `json:"template"`
	Path     *string          `json:"path,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	Force    *bool            `json:"force,omitempty"`
}

type StackInitResult struct {
	Status   string `json:"status"`
	Template string `json:"template"`
	Root     string `json:"root"`
}

type StackRuntimeInput struct {
	Services []string `json:"services,omitempty"`
	Build    *bool    `json:"build,omitempty"`
}

// The stack overview aggregate — the root fields the web console reads as one.
type StackSnapshot struct {
	Health         *MutationResult             `json:"health,omitempty"`
	StackStatus    *api.StackStatusResponse    `json:"stackStatus,omitempty"`
	Services       []*api.ServiceState         `json:"services"`
	Jobs           []*api.JobState             `json:"jobs"`
	Sources        []*api.SourceState          `json:"sources"`
	Workspaces     []*api.WorkspaceRef         `json:"workspaces"`
	Templates      []*api.TemplateDescriptor   `json:"templates"`
	Secrets        []*api.SecretRef            `json:"secrets"`
	GitOpsTopology *api.GitOpsTopologyResponse `json:"gitOpsTopology,omitempty"`
}

type StringComparisonExp struct {
	Eq      *string  `json:"_eq,omitempty"`
	Neq     *string  `json:"_neq,omitempty"`
	Gt      *string  `json:"_gt,omitempty"`
	Gte     *string  `json:"_gte,omitempty"`
	Lt      *string  `json:"_lt,omitempty"`
	Lte     *string  `json:"_lte,omitempty"`
	In      []string `json:"_in,omitempty"`
	Nin     []string `json:"_nin,omitempty"`
	Like    *string  `json:"_like,omitempty"`
	Nlike   *string  `json:"_nlike,omitempty"`
	Ilike   *string  `json:"_ilike,omitempty"`
	Nilike  *string  `json:"_nilike,omitempty"`
	Similar *string  `json:"_similar,omitempty"`
	IsNull  *bool    `json:"_is_null,omitempty"`
}

type Subscription struct {
}

type WorkspaceCreateInput struct {
	Template string           `json:"template"`
	Name     *string          `json:"name,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	TTL      *string          `json:"ttl,omitempty"`
	Sync     *bool            `json:"sync,omitempty"`
}

type JobsAggregate struct {
	Aggregate *JobsAggregateFields `json:"aggregate,omitempty"`
	Nodes     []*api.JobState      `json:"nodes"`
}

type JobsAggregateFields struct {
	Count int `json:"count"`
}

type JobsBoolExp struct {
	And     []*JobsBoolExp       `json:"_and,omitempty"`
	Or      []*JobsBoolExp       `json:"_or,omitempty"`
	Not     *JobsBoolExp         `json:"_not,omitempty"`
	ID      *StringComparisonExp `json:"id,omitempty"`
	Name    *StringComparisonExp `json:"name,omitempty"`
	Runtime *StringComparisonExp `json:"runtime,omitempty"`
}

type JobsOrderBy struct {
	ID      *OrderBy `json:"id,omitempty"`
	Name    *OrderBy `json:"name,omitempty"`
	Runtime *OrderBy `json:"runtime,omitempty"`
}

type SecretsAggregate struct {
	Aggregate *SecretsAggregateFields `json:"aggregate,omitempty"`
	Nodes     []*api.SecretRef        `json:"nodes"`
}

type SecretsAggregateFields struct {
	Count int `json:"count"`
}

type SecretsBoolExp struct {
	And       []*SecretsBoolExp     `json:"_and,omitempty"`
	Or        []*SecretsBoolExp     `json:"_or,omitempty"`
	Not       *SecretsBoolExp       `json:"_not,omitempty"`
	ID        *StringComparisonExp  `json:"id,omitempty"`
	Name      *StringComparisonExp  `json:"name,omitempty"`
	EnvVar    *StringComparisonExp  `json:"envVar,omitempty"`
	Declared  *BooleanComparisonExp `json:"declared,omitempty"`
	HasValue  *BooleanComparisonExp `json:"hasValue,omitempty"`
	Required  *BooleanComparisonExp `json:"required,omitempty"`
	Generated *BooleanComparisonExp `json:"generated,omitempty"`
}

type SecretsInsertInput struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type SecretsOrderBy struct {
	ID       *OrderBy `json:"id,omitempty"`
	Name     *OrderBy `json:"name,omitempty"`
	EnvVar   *OrderBy `json:"envVar,omitempty"`
	Declared *OrderBy `json:"declared,omitempty"`
	HasValue *OrderBy `json:"hasValue,omitempty"`
}

type SecretsPkColumnsInput struct {
	ID string `json:"id"`
}

type SecretsSetInput struct {
	Value *string `json:"value,omitempty"`
}

type ServicesAggregate struct {
	Aggregate *ServicesAggregateFields `json:"aggregate,omitempty"`
	Nodes     []*api.ServiceState      `json:"nodes"`
}

type ServicesAggregateFields struct {
	Count int `json:"count"`
}

type ServicesBoolExp struct {
	And     []*ServicesBoolExp   `json:"_and,omitempty"`
	Or      []*ServicesBoolExp   `json:"_or,omitempty"`
	Not     *ServicesBoolExp     `json:"_not,omitempty"`
	ID      *StringComparisonExp `json:"id,omitempty"`
	Name    *StringComparisonExp `json:"name,omitempty"`
	Runtime *StringComparisonExp `json:"runtime,omitempty"`
	Status  *StringComparisonExp `json:"status,omitempty"`
	Health  *StringComparisonExp `json:"health,omitempty"`
}

type ServicesGroup struct {
	Key       *ServicesGroupKey        `json:"key"`
	Aggregate *ServicesAggregateFields `json:"aggregate"`
}

type ServicesInsertInput struct {
	Template  string           `json:"template"`
	Workspace string           `json:"workspace"`
	Name      *string          `json:"name,omitempty"`
	Start     *bool            `json:"start,omitempty"`
	Inputs    []*KeyValueInput `json:"inputs,omitempty"`
}

type ServicesOrderBy struct {
	ID      *OrderBy `json:"id,omitempty"`
	Name    *OrderBy `json:"name,omitempty"`
	Runtime *OrderBy `json:"runtime,omitempty"`
	Status  *OrderBy `json:"status,omitempty"`
	Health  *OrderBy `json:"health,omitempty"`
}

type ServicesPkColumnsInput struct {
	ID string `json:"id"`
}

type ServicesSetInput struct {
	Runtime *string          `json:"runtime,omitempty"`
	Image   *string          `json:"image,omitempty"`
	Command []string         `json:"command,omitempty"`
	Mounts  []string         `json:"mounts,omitempty"`
	Env     []*KeyValueInput `json:"env,omitempty"`
	Ports   []string         `json:"ports,omitempty"`
	Workdir *string          `json:"workdir,omitempty"`
	Start   *bool            `json:"start,omitempty"`
}

type SourcesAggregate struct {
	Aggregate *SourcesAggregateFields `json:"aggregate,omitempty"`
	Nodes     []*api.SourceState      `json:"nodes"`
}

type SourcesAggregateFields struct {
	Count int               `json:"count"`
	Sum   *SourcesSumFields `json:"sum,omitempty"`
	Avg   *SourcesAvgFields `json:"avg,omitempty"`
	Min   *SourcesMinFields `json:"min,omitempty"`
	Max   *SourcesMaxFields `json:"max,omitempty"`
}

type SourcesAvgFields struct {
	Ahead  *float64 `json:"ahead,omitempty"`
	Behind *float64 `json:"behind,omitempty"`
}

type SourcesBoolExp struct {
	And    []*SourcesBoolExp     `json:"_and,omitempty"`
	Or     []*SourcesBoolExp     `json:"_or,omitempty"`
	Not    *SourcesBoolExp       `json:"_not,omitempty"`
	ID     *StringComparisonExp  `json:"id,omitempty"`
	Name   *StringComparisonExp  `json:"name,omitempty"`
	Kind   *StringComparisonExp  `json:"kind,omitempty"`
	State  *StringComparisonExp  `json:"state,omitempty"`
	Branch *StringComparisonExp  `json:"branch,omitempty"`
	Exists *BooleanComparisonExp `json:"exists,omitempty"`
	Dirty  *BooleanComparisonExp `json:"dirty,omitempty"`
	Pushed *BooleanComparisonExp `json:"pushed,omitempty"`
	Ahead  *IntComparisonExp     `json:"ahead,omitempty"`
	Behind *IntComparisonExp     `json:"behind,omitempty"`
}

type SourcesGroup struct {
	Key       *SourcesGroupKey        `json:"key"`
	Aggregate *SourcesAggregateFields `json:"aggregate"`
}

type SourcesMaxFields struct {
	Ahead  *int `json:"ahead,omitempty"`
	Behind *int `json:"behind,omitempty"`
}

type SourcesMinFields struct {
	Ahead  *int `json:"ahead,omitempty"`
	Behind *int `json:"behind,omitempty"`
}

type SourcesOrderBy struct {
	ID     *OrderBy `json:"id,omitempty"`
	Name   *OrderBy `json:"name,omitempty"`
	Kind   *OrderBy `json:"kind,omitempty"`
	State  *OrderBy `json:"state,omitempty"`
	Branch *OrderBy `json:"branch,omitempty"`
	Ahead  *OrderBy `json:"ahead,omitempty"`
	Behind *OrderBy `json:"behind,omitempty"`
}

type SourcesSumFields struct {
	Ahead  *int `json:"ahead,omitempty"`
	Behind *int `json:"behind,omitempty"`
}

type TemplatesAggregate struct {
	Aggregate *TemplatesAggregateFields `json:"aggregate,omitempty"`
	Nodes     []*api.TemplateDescriptor `json:"nodes"`
}

type TemplatesAggregateFields struct {
	Count int `json:"count"`
}

type TemplatesBoolExp struct {
	And  []*TemplatesBoolExp  `json:"_and,omitempty"`
	Or   []*TemplatesBoolExp  `json:"_or,omitempty"`
	Not  *TemplatesBoolExp    `json:"_not,omitempty"`
	ID   *StringComparisonExp `json:"id,omitempty"`
	Ref  *StringComparisonExp `json:"ref,omitempty"`
	Kind *StringComparisonExp `json:"kind,omitempty"`
	Name *StringComparisonExp `json:"name,omitempty"`
}

type TemplatesOrderBy struct {
	ID   *OrderBy `json:"id,omitempty"`
	Ref  *OrderBy `json:"ref,omitempty"`
	Kind *OrderBy `json:"kind,omitempty"`
	Name *OrderBy `json:"name,omitempty"`
}

type WorkspacesAggregate struct {
	Aggregate *WorkspacesAggregateFields `json:"aggregate,omitempty"`
	Nodes     []*api.WorkspaceRef        `json:"nodes"`
}

type WorkspacesAggregateFields struct {
	Count int `json:"count"`
}

type WorkspacesBoolExp struct {
	And      []*WorkspacesBoolExp `json:"_and,omitempty"`
	Or       []*WorkspacesBoolExp `json:"_or,omitempty"`
	Not      *WorkspacesBoolExp   `json:"_not,omitempty"`
	ID       *StringComparisonExp `json:"id,omitempty"`
	Name     *StringComparisonExp `json:"name,omitempty"`
	Template *StringComparisonExp `json:"template,omitempty"`
}

type WorkspacesInsertInput struct {
	Template string           `json:"template"`
	Name     *string          `json:"name,omitempty"`
	TTL      *string          `json:"ttl,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	Sync     *bool            `json:"sync,omitempty"`
}

type WorkspacesOrderBy struct {
	ID       *OrderBy `json:"id,omitempty"`
	Name     *OrderBy `json:"name,omitempty"`
	Template *OrderBy `json:"template,omitempty"`
}

type WorkspacesPkColumnsInput struct {
	ID string `json:"id"`
}

type WorkspacesSetInput struct {
	TTL    *string          `json:"ttl,omitempty"`
	Inputs []*KeyValueInput `json:"inputs,omitempty"`
}

type Granularity string

const (
	GranularityYear          Granularity = "YEAR"
	GranularityQuarter       Granularity = "QUARTER"
	GranularityMonth         Granularity = "MONTH"
	GranularityWeek          Granularity = "WEEK"
	GranularityDay           Granularity = "DAY"
	GranularityHour          Granularity = "HOUR"
	GranularityMinute        Granularity = "MINUTE"
	GranularitySecond        Granularity = "SECOND"
	GranularityYearNumber    Granularity = "YEAR_NUMBER"
	GranularityQuarterNumber Granularity = "QUARTER_NUMBER"
	GranularityMonthNumber   Granularity = "MONTH_NUMBER"
	GranularityIsoWeekNumber Granularity = "ISO_WEEK_NUMBER"
	GranularityDayOfYear     Granularity = "DAY_OF_YEAR"
	GranularityDayOfMonth    Granularity = "DAY_OF_MONTH"
	GranularityDayOfWeek     Granularity = "DAY_OF_WEEK"
	GranularityHourNumber    Granularity = "HOUR_NUMBER"
	GranularityMinuteNumber  Granularity = "MINUTE_NUMBER"
	GranularitySecondNumber  Granularity = "SECOND_NUMBER"
)

var AllGranularity = []Granularity{
	GranularityYear,
	GranularityQuarter,
	GranularityMonth,
	GranularityWeek,
	GranularityDay,
	GranularityHour,
	GranularityMinute,
	GranularitySecond,
	GranularityYearNumber,
	GranularityQuarterNumber,
	GranularityMonthNumber,
	GranularityIsoWeekNumber,
	GranularityDayOfYear,
	GranularityDayOfMonth,
	GranularityDayOfWeek,
	GranularityHourNumber,
	GranularityMinuteNumber,
	GranularitySecondNumber,
}

func (e Granularity) IsValid() bool {
	switch e {
	case GranularityYear, GranularityQuarter, GranularityMonth, GranularityWeek, GranularityDay, GranularityHour, GranularityMinute, GranularitySecond, GranularityYearNumber, GranularityQuarterNumber, GranularityMonthNumber, GranularityIsoWeekNumber, GranularityDayOfYear, GranularityDayOfMonth, GranularityDayOfWeek, GranularityHourNumber, GranularityMinuteNumber, GranularitySecondNumber:
		return true
	}
	return false
}

func (e Granularity) String() string {
	return string(e)
}

func (e *Granularity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Granularity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Granularity", str)
	}
	return nil
}

func (e Granularity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Granularity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Granularity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServicesGroupableField string

const (
	ServicesGroupableFieldStatus  ServicesGroupableField = "STATUS"
	ServicesGroupableFieldRuntime ServicesGroupableField = "RUNTIME"
	ServicesGroupableFieldHealth  ServicesGroupableField = "HEALTH"
)

var AllServicesGroupableField = []ServicesGroupableField{
	ServicesGroupableFieldStatus,
	ServicesGroupableFieldRuntime,
	ServicesGroupableFieldHealth,
}

func (e ServicesGroupableField) IsValid() bool {
	switch e {
	case ServicesGroupableFieldStatus, ServicesGroupableFieldRuntime, ServicesGroupableFieldHealth:
		return true
	}
	return false
}

func (e ServicesGroupableField) String() string {
	return string(e)
}

func (e *ServicesGroupableField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServicesGroupableField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServicesGroupableField", str)
	}
	return nil
}

func (e ServicesGroupableField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServicesGroupableField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServicesGroupableField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SourcesGroupableField string

const (
	SourcesGroupableFieldKind   SourcesGroupableField = "KIND"
	SourcesGroupableFieldState  SourcesGroupableField = "STATE"
	SourcesGroupableFieldBranch SourcesGroupableField = "BRANCH"
	SourcesGroupableFieldDirty  SourcesGroupableField = "DIRTY"
	SourcesGroupableFieldPushed SourcesGroupableField = "PUSHED"
)

var AllSourcesGroupableField = []SourcesGroupableField{
	SourcesGroupableFieldKind,
	SourcesGroupableFieldState,
	SourcesGroupableFieldBranch,
	SourcesGroupableFieldDirty,
	SourcesGroupableFieldPushed,
}

func (e SourcesGroupableField) IsValid() bool {
	switch e {
	case SourcesGroupableFieldKind, SourcesGroupableFieldState, SourcesGroupableFieldBranch, SourcesGroupableFieldDirty, SourcesGroupableFieldPushed:
		return true
	}
	return false
}

func (e SourcesGroupableField) String() string {
	return string(e)
}

func (e *SourcesGroupableField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SourcesGroupableField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SourcesGroupableField", str)
	}
	return nil
}

func (e SourcesGroupableField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SourcesGroupableField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SourcesGroupableField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderBy string

const (
	OrderByAsc            OrderBy = "asc"
	OrderByAscNullsFirst  OrderBy = "asc_nulls_first"
	OrderByAscNullsLast   OrderBy = "asc_nulls_last"
	OrderByDesc           OrderBy = "desc"
	OrderByDescNullsFirst OrderBy = "desc_nulls_first"
	OrderByDescNullsLast  OrderBy = "desc_nulls_last"
)

var AllOrderBy = []OrderBy{
	OrderByAsc,
	OrderByAscNullsFirst,
	OrderByAscNullsLast,
	OrderByDesc,
	OrderByDescNullsFirst,
	OrderByDescNullsLast,
}

func (e OrderBy) IsValid() bool {
	switch e {
	case OrderByAsc, OrderByAscNullsFirst, OrderByAscNullsLast, OrderByDesc, OrderByDescNullsFirst, OrderByDescNullsLast:
		return true
	}
	return false
}

func (e OrderBy) String() string {
	return string(e)
}

func (e *OrderBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid order_by", str)
	}
	return nil
}

func (e OrderBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
