// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/ang-ee/angee-operator/api"
)

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type MutationResult struct {
	Status  string  `json:"status"`
	Name    *string `json:"name,omitempty"`
	Message *string `json:"message,omitempty"`
}

type Query struct {
}

type ServiceCreateInput struct {
	Template  string           `json:"template"`
	Workspace string           `json:"workspace"`
	Inputs    []*KeyValueInput `json:"inputs,omitempty"`
	Name      *string          `json:"name,omitempty"`
	Start     *bool            `json:"start,omitempty"`
}

type ServiceInput struct {
	Name    *string          `json:"name,omitempty"`
	Runtime *string          `json:"runtime,omitempty"`
	Image   *string          `json:"image,omitempty"`
	Command []string         `json:"command,omitempty"`
	Mounts  []string         `json:"mounts,omitempty"`
	Env     []*KeyValueInput `json:"env,omitempty"`
	Ports   []string         `json:"ports,omitempty"`
	Workdir *string          `json:"workdir,omitempty"`
	Start   *bool            `json:"start,omitempty"`
}

type StackInitInput struct {
	Template string           `json:"template"`
	Path     *string          `json:"path,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	Force    *bool            `json:"force,omitempty"`
}

type StackInitResult struct {
	Status   string `json:"status"`
	Template string `json:"template"`
	Root     string `json:"root"`
}

type StackRuntimeInput struct {
	Services []string `json:"services,omitempty"`
	Build    *bool    `json:"build,omitempty"`
}

// The stack overview aggregate — the root fields the web console reads as one.
// Mirrors the Query-root types so a client can subscribe to the whole snapshot
// and field-prune via its selection set.
type StackSnapshot struct {
	Health         *MutationResult             `json:"health,omitempty"`
	StackStatus    *api.StackStatusResponse    `json:"stackStatus,omitempty"`
	Services       []*api.ServiceState         `json:"services"`
	Jobs           []*api.JobState             `json:"jobs"`
	Sources        []*api.SourceState          `json:"sources"`
	Workspaces     []*api.WorkspaceRef         `json:"workspaces"`
	Templates      []*api.TemplateDescriptor   `json:"templates"`
	Secrets        []*api.SecretRef            `json:"secrets"`
	GitOpsTopology *api.GitOpsTopologyResponse `json:"gitOpsTopology,omitempty"`
}

type Subscription struct {
}

type WorkspaceCreateInput struct {
	Template string           `json:"template"`
	Name     *string          `json:"name,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	TTL      *string          `json:"ttl,omitempty"`
}

type WorkspaceUpdateInput struct {
	Inputs []*KeyValueInput `json:"inputs,omitempty"`
	TTL    *string          `json:"ttl,omitempty"`
}
