#!/usr/bin/env sh
# Regenerate the Homebrew formula for a released version.
#
# Usage: scripts/update-homebrew-formula.sh <version> [output-path]
#
#   version      release tag, with or without the leading "v" (e.g. v0.8.6)
#   output-path  where to write the formula (default: ./angee.rb)
#
# Checksums are read from the release's SHA256SUMS asset, so the release must
# already exist. Requires `gh` (authenticated) and `curl`.
#
# The release workflow calls this and pushes the result to ang-ee/homebrew-tap.
# Run it by hand only to repair a formula out of band.
set -eu

REPO="ang-ee/angee-operator"

if [ $# -lt 1 ]; then
  echo "usage: $0 <version> [output-path]" >&2
  exit 2
fi

VERSION="${1#v}"
TAG="v${VERSION}"
OUT="${2:-angee.rb}"

if [ -z "$VERSION" ]; then
  echo "error: empty version" >&2
  exit 2
fi

SUMS="$(gh release view "$TAG" --repo "$REPO" --json assets \
  --jq '.assets[] | select(.name == "SHA256SUMS") | .url' 2>/dev/null || true)"
if [ -z "$SUMS" ]; then
  echo "error: $TAG has no SHA256SUMS asset (is the release published?)" >&2
  exit 1
fi

CHECKSUMS="$(gh release download "$TAG" --repo "$REPO" -p SHA256SUMS -O - 2>/dev/null)"
if [ -z "$CHECKSUMS" ]; then
  echo "error: could not download SHA256SUMS for $TAG" >&2
  exit 1
fi

# sha_for <asset-name> — pull one checksum out of SHA256SUMS, failing loudly
# rather than emitting a formula with an empty sha256 that would install
# anything the URL happens to serve.
sha_for() {
  sum="$(printf '%s\n' "$CHECKSUMS" | awk -v name="$1" '$2 == name { print $1; exit }')"
  if [ -z "$sum" ]; then
    echo "error: no checksum for $1 in $TAG SHA256SUMS" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

DARWIN_AMD64="$(sha_for angee-darwin-amd64.tar.gz)"
DARWIN_ARM64="$(sha_for angee-darwin-arm64.tar.gz)"
LINUX_AMD64="$(sha_for angee-linux-amd64.tar.gz)"
LINUX_ARM64="$(sha_for angee-linux-arm64.tar.gz)"

BASE="https://github.com/${REPO}/releases/download/${TAG}"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<FORMULA
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh in ang-ee/angee-operator.
# Every release overwrites this file — edit the generator, not this.
class Angee < Formula
  desc "Self-managed stack manager for agent-native applications"
  homepage "https://angee.ai"
  # No \`version\`: Homebrew scans ${VERSION} from the release URLs, and
  # \`brew audit --strict\` rejects declaring it twice.

  # process-compose runs \`runtime: local\` services. Installing it here also
  # bypasses angee's fallback path, which otherwise prompts to \`go install\` it
  # and needs a Go toolchain on the host.
  #
  # This points at our own vendored copy, not f1bonacc1/tap: Homebrew 6 will
  # not auto-tap a third-party dependency and additionally requires an explicit
  # \`brew trust\` for it, which would turn installation into three commands.
  #
  # git is not declared: Homebrew itself requires it, so it is always present.
  depends_on "ang-ee/tap/process-compose"

  on_macos do
    on_intel do
      url "${BASE}/angee-darwin-amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
    end
    on_arm do
      url "${BASE}/angee-darwin-arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE}/angee-linux-amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
    end
    on_arm do
      url "${BASE}/angee-linux-arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
  end

  def install
    bin.install "angee"
    bin.install "angee-operator"
  end

  def caveats
    <<~CAVEATS
      Docker is NOT installed by this formula. It is required only for
      \`runtime: container\` services and container jobs. If you need it:

        brew install --cask docker      # Docker Desktop
        brew install --cask orbstack    # OrbStack
        brew install colima docker      # Colima + docker CLI

      \`runtime: local\` services use process-compose, installed as a dependency.
      A stack using neither needs no container runtime at all.

      Getting started:  https://docs.angee.ai/guide/getting-started
    CAVEATS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/angee --version")
    assert_match version.to_s, shell_output("#{bin}/angee-operator --version")

    # Exercise command wiring without reaching for a container runtime.
    system bin/"angee", "--help"
  end
end
FORMULA

echo "wrote $OUT for $TAG"
